// Code generated by ent, DO NOT EDIT.

package creemrefundevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the creemrefundevent type in the database.
	Label = "creem_refund_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEventID holds the string denoting the event_id field in the database.
	FieldEventID = "event_id"
	// FieldProviderRefundID holds the string denoting the provider_refund_id field in the database.
	FieldProviderRefundID = "provider_refund_id"
	// FieldProviderInstanceID holds the string denoting the provider_instance_id field in the database.
	FieldProviderInstanceID = "provider_instance_id"
	// FieldPaymentOrderID holds the string denoting the payment_order_id field in the database.
	FieldPaymentOrderID = "payment_order_id"
	// FieldTransactionID holds the string denoting the transaction_id field in the database.
	FieldTransactionID = "transaction_id"
	// FieldRefundAmountMinor holds the string denoting the refund_amount_minor field in the database.
	FieldRefundAmountMinor = "refund_amount_minor"
	// FieldCumulativeRefundedMinor holds the string denoting the cumulative_refunded_minor field in the database.
	FieldCumulativeRefundedMinor = "cumulative_refunded_minor"
	// FieldTransactionAmountPaidMinor holds the string denoting the transaction_amount_paid_minor field in the database.
	FieldTransactionAmountPaidMinor = "transaction_amount_paid_minor"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldRefundRatio holds the string denoting the refund_ratio field in the database.
	FieldRefundRatio = "refund_ratio"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRecoverySnapshot holds the string denoting the recovery_snapshot field in the database.
	FieldRecoverySnapshot = "recovery_snapshot"
	// FieldRawPayload holds the string denoting the raw_payload field in the database.
	FieldRawPayload = "raw_payload"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldProcessedAt holds the string denoting the processed_at field in the database.
	FieldProcessedAt = "processed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the creemrefundevent in the database.
	Table = "creem_refund_events"
)

// Columns holds all SQL columns for creemrefundevent fields.
var Columns = []string{
	FieldID,
	FieldEventID,
	FieldProviderRefundID,
	FieldProviderInstanceID,
	FieldPaymentOrderID,
	FieldTransactionID,
	FieldRefundAmountMinor,
	FieldCumulativeRefundedMinor,
	FieldTransactionAmountPaidMinor,
	FieldCurrency,
	FieldRefundRatio,
	FieldStatus,
	FieldRecoverySnapshot,
	FieldRawPayload,
	FieldAttempts,
	FieldLastError,
	FieldProcessedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventIDValidator is a validator for the "event_id" field. It is called by the builders before save.
	EventIDValidator func(string) error
	// ProviderRefundIDValidator is a validator for the "provider_refund_id" field. It is called by the builders before save.
	ProviderRefundIDValidator func(string) error
	// TransactionIDValidator is a validator for the "transaction_id" field. It is called by the builders before save.
	TransactionIDValidator func(string) error
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultRefundRatio holds the default value on creation for the "refund_ratio" field.
	DefaultRefundRatio float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts int
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CreemRefundEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventID orders the results by the event_id field.
func ByEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventID, opts...).ToFunc()
}

// ByProviderRefundID orders the results by the provider_refund_id field.
func ByProviderRefundID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderRefundID, opts...).ToFunc()
}

// ByProviderInstanceID orders the results by the provider_instance_id field.
func ByProviderInstanceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderInstanceID, opts...).ToFunc()
}

// ByPaymentOrderID orders the results by the payment_order_id field.
func ByPaymentOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentOrderID, opts...).ToFunc()
}

// ByTransactionID orders the results by the transaction_id field.
func ByTransactionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransactionID, opts...).ToFunc()
}

// ByRefundAmountMinor orders the results by the refund_amount_minor field.
func ByRefundAmountMinor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundAmountMinor, opts...).ToFunc()
}

// ByCumulativeRefundedMinor orders the results by the cumulative_refunded_minor field.
func ByCumulativeRefundedMinor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCumulativeRefundedMinor, opts...).ToFunc()
}

// ByTransactionAmountPaidMinor orders the results by the transaction_amount_paid_minor field.
func ByTransactionAmountPaidMinor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransactionAmountPaidMinor, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByRefundRatio orders the results by the refund_ratio field.
func ByRefundRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundRatio, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAttempts orders the results by the attempts field.
func ByAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempts, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByProcessedAt orders the results by the processed_at field.
func ByProcessedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
