// Code generated by ent, DO NOT EDIT.

package subscriptionplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldGroupID, v))
}

// PlanScope applies equality check predicate on the "plan_scope" field. It's identical to PlanScopeEQ.
func PlanScope(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldPlanScope, v))
}

// PlanCategory applies equality check predicate on the "plan_category" field. It's identical to PlanCategoryEQ.
func PlanCategory(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldPlanCategory, v))
}

// ApplicableGroupMode applies equality check predicate on the "applicable_group_mode" field. It's identical to ApplicableGroupModeEQ.
func ApplicableGroupMode(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldApplicableGroupMode, v))
}

// TierRank applies equality check predicate on the "tier_rank" field. It's identical to TierRankEQ.
func TierRank(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldTierRank, v))
}

// QuotaPeriod applies equality check predicate on the "quota_period" field. It's identical to QuotaPeriodEQ.
func QuotaPeriod(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldQuotaPeriod, v))
}

// QuotaPerPeriodUsd applies equality check predicate on the "quota_per_period_usd" field. It's identical to QuotaPerPeriodUsdEQ.
func QuotaPerPeriodUsd(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldQuotaPerPeriodUsd, v))
}

// MonthlyMaxUsd applies equality check predicate on the "monthly_max_usd" field. It's identical to MonthlyMaxUsdEQ.
func MonthlyMaxUsd(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldMonthlyMaxUsd, v))
}

// SpeedTier applies equality check predicate on the "speed_tier" field. It's identical to SpeedTierEQ.
func SpeedTier(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldSpeedTier, v))
}

// SupportTier applies equality check predicate on the "support_tier" field. It's identical to SupportTierEQ.
func SupportTier(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldSupportTier, v))
}

// PublicBadge applies equality check predicate on the "public_badge" field. It's identical to PublicBadgeEQ.
func PublicBadge(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldPublicBadge, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldDescription, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldPrice, v))
}

// OriginalPrice applies equality check predicate on the "original_price" field. It's identical to OriginalPriceEQ.
func OriginalPrice(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldOriginalPrice, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldCurrency, v))
}

// ValidityDays applies equality check predicate on the "validity_days" field. It's identical to ValidityDaysEQ.
func ValidityDays(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityUnit applies equality check predicate on the "validity_unit" field. It's identical to ValidityUnitEQ.
func ValidityUnit(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldValidityUnit, v))
}

// Features applies equality check predicate on the "features" field. It's identical to FeaturesEQ.
func Features(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldFeatures, v))
}

// ProductName applies equality check predicate on the "product_name" field. It's identical to ProductNameEQ.
func ProductName(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldProductName, v))
}

// ForSale applies equality check predicate on the "for_sale" field. It's identical to ForSaleEQ.
func ForSale(v bool) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldForSale, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotNull(FieldGroupID))
}

// PlanScopeEQ applies the EQ predicate on the "plan_scope" field.
func PlanScopeEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldPlanScope, v))
}

// PlanScopeNEQ applies the NEQ predicate on the "plan_scope" field.
func PlanScopeNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldPlanScope, v))
}

// PlanScopeIn applies the In predicate on the "plan_scope" field.
func PlanScopeIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldPlanScope, vs...))
}

// PlanScopeNotIn applies the NotIn predicate on the "plan_scope" field.
func PlanScopeNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldPlanScope, vs...))
}

// PlanScopeGT applies the GT predicate on the "plan_scope" field.
func PlanScopeGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldPlanScope, v))
}

// PlanScopeGTE applies the GTE predicate on the "plan_scope" field.
func PlanScopeGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldPlanScope, v))
}

// PlanScopeLT applies the LT predicate on the "plan_scope" field.
func PlanScopeLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldPlanScope, v))
}

// PlanScopeLTE applies the LTE predicate on the "plan_scope" field.
func PlanScopeLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldPlanScope, v))
}

// PlanScopeContains applies the Contains predicate on the "plan_scope" field.
func PlanScopeContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldPlanScope, v))
}

// PlanScopeHasPrefix applies the HasPrefix predicate on the "plan_scope" field.
func PlanScopeHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldPlanScope, v))
}

// PlanScopeHasSuffix applies the HasSuffix predicate on the "plan_scope" field.
func PlanScopeHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldPlanScope, v))
}

// PlanScopeEqualFold applies the EqualFold predicate on the "plan_scope" field.
func PlanScopeEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldPlanScope, v))
}

// PlanScopeContainsFold applies the ContainsFold predicate on the "plan_scope" field.
func PlanScopeContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldPlanScope, v))
}

// PlanCategoryEQ applies the EQ predicate on the "plan_category" field.
func PlanCategoryEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldPlanCategory, v))
}

// PlanCategoryNEQ applies the NEQ predicate on the "plan_category" field.
func PlanCategoryNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldPlanCategory, v))
}

// PlanCategoryIn applies the In predicate on the "plan_category" field.
func PlanCategoryIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldPlanCategory, vs...))
}

// PlanCategoryNotIn applies the NotIn predicate on the "plan_category" field.
func PlanCategoryNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldPlanCategory, vs...))
}

// PlanCategoryGT applies the GT predicate on the "plan_category" field.
func PlanCategoryGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldPlanCategory, v))
}

// PlanCategoryGTE applies the GTE predicate on the "plan_category" field.
func PlanCategoryGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldPlanCategory, v))
}

// PlanCategoryLT applies the LT predicate on the "plan_category" field.
func PlanCategoryLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldPlanCategory, v))
}

// PlanCategoryLTE applies the LTE predicate on the "plan_category" field.
func PlanCategoryLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldPlanCategory, v))
}

// PlanCategoryContains applies the Contains predicate on the "plan_category" field.
func PlanCategoryContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldPlanCategory, v))
}

// PlanCategoryHasPrefix applies the HasPrefix predicate on the "plan_category" field.
func PlanCategoryHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldPlanCategory, v))
}

// PlanCategoryHasSuffix applies the HasSuffix predicate on the "plan_category" field.
func PlanCategoryHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldPlanCategory, v))
}

// PlanCategoryEqualFold applies the EqualFold predicate on the "plan_category" field.
func PlanCategoryEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldPlanCategory, v))
}

// PlanCategoryContainsFold applies the ContainsFold predicate on the "plan_category" field.
func PlanCategoryContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldPlanCategory, v))
}

// ApplicableGroupModeEQ applies the EQ predicate on the "applicable_group_mode" field.
func ApplicableGroupModeEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldApplicableGroupMode, v))
}

// ApplicableGroupModeNEQ applies the NEQ predicate on the "applicable_group_mode" field.
func ApplicableGroupModeNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldApplicableGroupMode, v))
}

// ApplicableGroupModeIn applies the In predicate on the "applicable_group_mode" field.
func ApplicableGroupModeIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldApplicableGroupMode, vs...))
}

// ApplicableGroupModeNotIn applies the NotIn predicate on the "applicable_group_mode" field.
func ApplicableGroupModeNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldApplicableGroupMode, vs...))
}

// ApplicableGroupModeGT applies the GT predicate on the "applicable_group_mode" field.
func ApplicableGroupModeGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldApplicableGroupMode, v))
}

// ApplicableGroupModeGTE applies the GTE predicate on the "applicable_group_mode" field.
func ApplicableGroupModeGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldApplicableGroupMode, v))
}

// ApplicableGroupModeLT applies the LT predicate on the "applicable_group_mode" field.
func ApplicableGroupModeLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldApplicableGroupMode, v))
}

// ApplicableGroupModeLTE applies the LTE predicate on the "applicable_group_mode" field.
func ApplicableGroupModeLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldApplicableGroupMode, v))
}

// ApplicableGroupModeContains applies the Contains predicate on the "applicable_group_mode" field.
func ApplicableGroupModeContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldApplicableGroupMode, v))
}

// ApplicableGroupModeHasPrefix applies the HasPrefix predicate on the "applicable_group_mode" field.
func ApplicableGroupModeHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldApplicableGroupMode, v))
}

// ApplicableGroupModeHasSuffix applies the HasSuffix predicate on the "applicable_group_mode" field.
func ApplicableGroupModeHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldApplicableGroupMode, v))
}

// ApplicableGroupModeEqualFold applies the EqualFold predicate on the "applicable_group_mode" field.
func ApplicableGroupModeEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldApplicableGroupMode, v))
}

// ApplicableGroupModeContainsFold applies the ContainsFold predicate on the "applicable_group_mode" field.
func ApplicableGroupModeContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldApplicableGroupMode, v))
}

// TierRankEQ applies the EQ predicate on the "tier_rank" field.
func TierRankEQ(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldTierRank, v))
}

// TierRankNEQ applies the NEQ predicate on the "tier_rank" field.
func TierRankNEQ(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldTierRank, v))
}

// TierRankIn applies the In predicate on the "tier_rank" field.
func TierRankIn(vs ...int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldTierRank, vs...))
}

// TierRankNotIn applies the NotIn predicate on the "tier_rank" field.
func TierRankNotIn(vs ...int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldTierRank, vs...))
}

// TierRankGT applies the GT predicate on the "tier_rank" field.
func TierRankGT(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldTierRank, v))
}

// TierRankGTE applies the GTE predicate on the "tier_rank" field.
func TierRankGTE(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldTierRank, v))
}

// TierRankLT applies the LT predicate on the "tier_rank" field.
func TierRankLT(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldTierRank, v))
}

// TierRankLTE applies the LTE predicate on the "tier_rank" field.
func TierRankLTE(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldTierRank, v))
}

// QuotaPeriodEQ applies the EQ predicate on the "quota_period" field.
func QuotaPeriodEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldQuotaPeriod, v))
}

// QuotaPeriodNEQ applies the NEQ predicate on the "quota_period" field.
func QuotaPeriodNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldQuotaPeriod, v))
}

// QuotaPeriodIn applies the In predicate on the "quota_period" field.
func QuotaPeriodIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldQuotaPeriod, vs...))
}

// QuotaPeriodNotIn applies the NotIn predicate on the "quota_period" field.
func QuotaPeriodNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldQuotaPeriod, vs...))
}

// QuotaPeriodGT applies the GT predicate on the "quota_period" field.
func QuotaPeriodGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldQuotaPeriod, v))
}

// QuotaPeriodGTE applies the GTE predicate on the "quota_period" field.
func QuotaPeriodGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldQuotaPeriod, v))
}

// QuotaPeriodLT applies the LT predicate on the "quota_period" field.
func QuotaPeriodLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldQuotaPeriod, v))
}

// QuotaPeriodLTE applies the LTE predicate on the "quota_period" field.
func QuotaPeriodLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldQuotaPeriod, v))
}

// QuotaPeriodContains applies the Contains predicate on the "quota_period" field.
func QuotaPeriodContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldQuotaPeriod, v))
}

// QuotaPeriodHasPrefix applies the HasPrefix predicate on the "quota_period" field.
func QuotaPeriodHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldQuotaPeriod, v))
}

// QuotaPeriodHasSuffix applies the HasSuffix predicate on the "quota_period" field.
func QuotaPeriodHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldQuotaPeriod, v))
}

// QuotaPeriodEqualFold applies the EqualFold predicate on the "quota_period" field.
func QuotaPeriodEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldQuotaPeriod, v))
}

// QuotaPeriodContainsFold applies the ContainsFold predicate on the "quota_period" field.
func QuotaPeriodContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldQuotaPeriod, v))
}

// QuotaPerPeriodUsdEQ applies the EQ predicate on the "quota_per_period_usd" field.
func QuotaPerPeriodUsdEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldQuotaPerPeriodUsd, v))
}

// QuotaPerPeriodUsdNEQ applies the NEQ predicate on the "quota_per_period_usd" field.
func QuotaPerPeriodUsdNEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldQuotaPerPeriodUsd, v))
}

// QuotaPerPeriodUsdIn applies the In predicate on the "quota_per_period_usd" field.
func QuotaPerPeriodUsdIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldQuotaPerPeriodUsd, vs...))
}

// QuotaPerPeriodUsdNotIn applies the NotIn predicate on the "quota_per_period_usd" field.
func QuotaPerPeriodUsdNotIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldQuotaPerPeriodUsd, vs...))
}

// QuotaPerPeriodUsdGT applies the GT predicate on the "quota_per_period_usd" field.
func QuotaPerPeriodUsdGT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldQuotaPerPeriodUsd, v))
}

// QuotaPerPeriodUsdGTE applies the GTE predicate on the "quota_per_period_usd" field.
func QuotaPerPeriodUsdGTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldQuotaPerPeriodUsd, v))
}

// QuotaPerPeriodUsdLT applies the LT predicate on the "quota_per_period_usd" field.
func QuotaPerPeriodUsdLT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldQuotaPerPeriodUsd, v))
}

// QuotaPerPeriodUsdLTE applies the LTE predicate on the "quota_per_period_usd" field.
func QuotaPerPeriodUsdLTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldQuotaPerPeriodUsd, v))
}

// MonthlyMaxUsdEQ applies the EQ predicate on the "monthly_max_usd" field.
func MonthlyMaxUsdEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldMonthlyMaxUsd, v))
}

// MonthlyMaxUsdNEQ applies the NEQ predicate on the "monthly_max_usd" field.
func MonthlyMaxUsdNEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldMonthlyMaxUsd, v))
}

// MonthlyMaxUsdIn applies the In predicate on the "monthly_max_usd" field.
func MonthlyMaxUsdIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldMonthlyMaxUsd, vs...))
}

// MonthlyMaxUsdNotIn applies the NotIn predicate on the "monthly_max_usd" field.
func MonthlyMaxUsdNotIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldMonthlyMaxUsd, vs...))
}

// MonthlyMaxUsdGT applies the GT predicate on the "monthly_max_usd" field.
func MonthlyMaxUsdGT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldMonthlyMaxUsd, v))
}

// MonthlyMaxUsdGTE applies the GTE predicate on the "monthly_max_usd" field.
func MonthlyMaxUsdGTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldMonthlyMaxUsd, v))
}

// MonthlyMaxUsdLT applies the LT predicate on the "monthly_max_usd" field.
func MonthlyMaxUsdLT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldMonthlyMaxUsd, v))
}

// MonthlyMaxUsdLTE applies the LTE predicate on the "monthly_max_usd" field.
func MonthlyMaxUsdLTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldMonthlyMaxUsd, v))
}

// SpeedTierEQ applies the EQ predicate on the "speed_tier" field.
func SpeedTierEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldSpeedTier, v))
}

// SpeedTierNEQ applies the NEQ predicate on the "speed_tier" field.
func SpeedTierNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldSpeedTier, v))
}

// SpeedTierIn applies the In predicate on the "speed_tier" field.
func SpeedTierIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldSpeedTier, vs...))
}

// SpeedTierNotIn applies the NotIn predicate on the "speed_tier" field.
func SpeedTierNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldSpeedTier, vs...))
}

// SpeedTierGT applies the GT predicate on the "speed_tier" field.
func SpeedTierGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldSpeedTier, v))
}

// SpeedTierGTE applies the GTE predicate on the "speed_tier" field.
func SpeedTierGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldSpeedTier, v))
}

// SpeedTierLT applies the LT predicate on the "speed_tier" field.
func SpeedTierLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldSpeedTier, v))
}

// SpeedTierLTE applies the LTE predicate on the "speed_tier" field.
func SpeedTierLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldSpeedTier, v))
}

// SpeedTierContains applies the Contains predicate on the "speed_tier" field.
func SpeedTierContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldSpeedTier, v))
}

// SpeedTierHasPrefix applies the HasPrefix predicate on the "speed_tier" field.
func SpeedTierHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldSpeedTier, v))
}

// SpeedTierHasSuffix applies the HasSuffix predicate on the "speed_tier" field.
func SpeedTierHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldSpeedTier, v))
}

// SpeedTierEqualFold applies the EqualFold predicate on the "speed_tier" field.
func SpeedTierEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldSpeedTier, v))
}

// SpeedTierContainsFold applies the ContainsFold predicate on the "speed_tier" field.
func SpeedTierContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldSpeedTier, v))
}

// SupportTierEQ applies the EQ predicate on the "support_tier" field.
func SupportTierEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldSupportTier, v))
}

// SupportTierNEQ applies the NEQ predicate on the "support_tier" field.
func SupportTierNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldSupportTier, v))
}

// SupportTierIn applies the In predicate on the "support_tier" field.
func SupportTierIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldSupportTier, vs...))
}

// SupportTierNotIn applies the NotIn predicate on the "support_tier" field.
func SupportTierNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldSupportTier, vs...))
}

// SupportTierGT applies the GT predicate on the "support_tier" field.
func SupportTierGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldSupportTier, v))
}

// SupportTierGTE applies the GTE predicate on the "support_tier" field.
func SupportTierGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldSupportTier, v))
}

// SupportTierLT applies the LT predicate on the "support_tier" field.
func SupportTierLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldSupportTier, v))
}

// SupportTierLTE applies the LTE predicate on the "support_tier" field.
func SupportTierLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldSupportTier, v))
}

// SupportTierContains applies the Contains predicate on the "support_tier" field.
func SupportTierContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldSupportTier, v))
}

// SupportTierHasPrefix applies the HasPrefix predicate on the "support_tier" field.
func SupportTierHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldSupportTier, v))
}

// SupportTierHasSuffix applies the HasSuffix predicate on the "support_tier" field.
func SupportTierHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldSupportTier, v))
}

// SupportTierEqualFold applies the EqualFold predicate on the "support_tier" field.
func SupportTierEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldSupportTier, v))
}

// SupportTierContainsFold applies the ContainsFold predicate on the "support_tier" field.
func SupportTierContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldSupportTier, v))
}

// PublicBadgeEQ applies the EQ predicate on the "public_badge" field.
func PublicBadgeEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldPublicBadge, v))
}

// PublicBadgeNEQ applies the NEQ predicate on the "public_badge" field.
func PublicBadgeNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldPublicBadge, v))
}

// PublicBadgeIn applies the In predicate on the "public_badge" field.
func PublicBadgeIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldPublicBadge, vs...))
}

// PublicBadgeNotIn applies the NotIn predicate on the "public_badge" field.
func PublicBadgeNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldPublicBadge, vs...))
}

// PublicBadgeGT applies the GT predicate on the "public_badge" field.
func PublicBadgeGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldPublicBadge, v))
}

// PublicBadgeGTE applies the GTE predicate on the "public_badge" field.
func PublicBadgeGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldPublicBadge, v))
}

// PublicBadgeLT applies the LT predicate on the "public_badge" field.
func PublicBadgeLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldPublicBadge, v))
}

// PublicBadgeLTE applies the LTE predicate on the "public_badge" field.
func PublicBadgeLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldPublicBadge, v))
}

// PublicBadgeContains applies the Contains predicate on the "public_badge" field.
func PublicBadgeContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldPublicBadge, v))
}

// PublicBadgeHasPrefix applies the HasPrefix predicate on the "public_badge" field.
func PublicBadgeHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldPublicBadge, v))
}

// PublicBadgeHasSuffix applies the HasSuffix predicate on the "public_badge" field.
func PublicBadgeHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldPublicBadge, v))
}

// PublicBadgeEqualFold applies the EqualFold predicate on the "public_badge" field.
func PublicBadgeEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldPublicBadge, v))
}

// PublicBadgeContainsFold applies the ContainsFold predicate on the "public_badge" field.
func PublicBadgeContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldPublicBadge, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldDescription, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldPrice, v))
}

// OriginalPriceEQ applies the EQ predicate on the "original_price" field.
func OriginalPriceEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldOriginalPrice, v))
}

// OriginalPriceNEQ applies the NEQ predicate on the "original_price" field.
func OriginalPriceNEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldOriginalPrice, v))
}

// OriginalPriceIn applies the In predicate on the "original_price" field.
func OriginalPriceIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldOriginalPrice, vs...))
}

// OriginalPriceNotIn applies the NotIn predicate on the "original_price" field.
func OriginalPriceNotIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldOriginalPrice, vs...))
}

// OriginalPriceGT applies the GT predicate on the "original_price" field.
func OriginalPriceGT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldOriginalPrice, v))
}

// OriginalPriceGTE applies the GTE predicate on the "original_price" field.
func OriginalPriceGTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldOriginalPrice, v))
}

// OriginalPriceLT applies the LT predicate on the "original_price" field.
func OriginalPriceLT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldOriginalPrice, v))
}

// OriginalPriceLTE applies the LTE predicate on the "original_price" field.
func OriginalPriceLTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldOriginalPrice, v))
}

// OriginalPriceIsNil applies the IsNil predicate on the "original_price" field.
func OriginalPriceIsNil() predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIsNull(FieldOriginalPrice))
}

// OriginalPriceNotNil applies the NotNil predicate on the "original_price" field.
func OriginalPriceNotNil() predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotNull(FieldOriginalPrice))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldCurrency, v))
}

// ValidityDaysEQ applies the EQ predicate on the "validity_days" field.
func ValidityDaysEQ(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityDaysNEQ applies the NEQ predicate on the "validity_days" field.
func ValidityDaysNEQ(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldValidityDays, v))
}

// ValidityDaysIn applies the In predicate on the "validity_days" field.
func ValidityDaysIn(vs ...int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldValidityDays, vs...))
}

// ValidityDaysNotIn applies the NotIn predicate on the "validity_days" field.
func ValidityDaysNotIn(vs ...int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldValidityDays, vs...))
}

// ValidityDaysGT applies the GT predicate on the "validity_days" field.
func ValidityDaysGT(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldValidityDays, v))
}

// ValidityDaysGTE applies the GTE predicate on the "validity_days" field.
func ValidityDaysGTE(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldValidityDays, v))
}

// ValidityDaysLT applies the LT predicate on the "validity_days" field.
func ValidityDaysLT(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldValidityDays, v))
}

// ValidityDaysLTE applies the LTE predicate on the "validity_days" field.
func ValidityDaysLTE(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldValidityDays, v))
}

// ValidityUnitEQ applies the EQ predicate on the "validity_unit" field.
func ValidityUnitEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldValidityUnit, v))
}

// ValidityUnitNEQ applies the NEQ predicate on the "validity_unit" field.
func ValidityUnitNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldValidityUnit, v))
}

// ValidityUnitIn applies the In predicate on the "validity_unit" field.
func ValidityUnitIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldValidityUnit, vs...))
}

// ValidityUnitNotIn applies the NotIn predicate on the "validity_unit" field.
func ValidityUnitNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldValidityUnit, vs...))
}

// ValidityUnitGT applies the GT predicate on the "validity_unit" field.
func ValidityUnitGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldValidityUnit, v))
}

// ValidityUnitGTE applies the GTE predicate on the "validity_unit" field.
func ValidityUnitGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldValidityUnit, v))
}

// ValidityUnitLT applies the LT predicate on the "validity_unit" field.
func ValidityUnitLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldValidityUnit, v))
}

// ValidityUnitLTE applies the LTE predicate on the "validity_unit" field.
func ValidityUnitLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldValidityUnit, v))
}

// ValidityUnitContains applies the Contains predicate on the "validity_unit" field.
func ValidityUnitContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldValidityUnit, v))
}

// ValidityUnitHasPrefix applies the HasPrefix predicate on the "validity_unit" field.
func ValidityUnitHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldValidityUnit, v))
}

// ValidityUnitHasSuffix applies the HasSuffix predicate on the "validity_unit" field.
func ValidityUnitHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldValidityUnit, v))
}

// ValidityUnitEqualFold applies the EqualFold predicate on the "validity_unit" field.
func ValidityUnitEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldValidityUnit, v))
}

// ValidityUnitContainsFold applies the ContainsFold predicate on the "validity_unit" field.
func ValidityUnitContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldValidityUnit, v))
}

// FeaturesEQ applies the EQ predicate on the "features" field.
func FeaturesEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldFeatures, v))
}

// FeaturesNEQ applies the NEQ predicate on the "features" field.
func FeaturesNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldFeatures, v))
}

// FeaturesIn applies the In predicate on the "features" field.
func FeaturesIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldFeatures, vs...))
}

// FeaturesNotIn applies the NotIn predicate on the "features" field.
func FeaturesNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldFeatures, vs...))
}

// FeaturesGT applies the GT predicate on the "features" field.
func FeaturesGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldFeatures, v))
}

// FeaturesGTE applies the GTE predicate on the "features" field.
func FeaturesGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldFeatures, v))
}

// FeaturesLT applies the LT predicate on the "features" field.
func FeaturesLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldFeatures, v))
}

// FeaturesLTE applies the LTE predicate on the "features" field.
func FeaturesLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldFeatures, v))
}

// FeaturesContains applies the Contains predicate on the "features" field.
func FeaturesContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldFeatures, v))
}

// FeaturesHasPrefix applies the HasPrefix predicate on the "features" field.
func FeaturesHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldFeatures, v))
}

// FeaturesHasSuffix applies the HasSuffix predicate on the "features" field.
func FeaturesHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldFeatures, v))
}

// FeaturesEqualFold applies the EqualFold predicate on the "features" field.
func FeaturesEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldFeatures, v))
}

// FeaturesContainsFold applies the ContainsFold predicate on the "features" field.
func FeaturesContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldFeatures, v))
}

// ProductNameEQ applies the EQ predicate on the "product_name" field.
func ProductNameEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldProductName, v))
}

// ProductNameNEQ applies the NEQ predicate on the "product_name" field.
func ProductNameNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldProductName, v))
}

// ProductNameIn applies the In predicate on the "product_name" field.
func ProductNameIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldProductName, vs...))
}

// ProductNameNotIn applies the NotIn predicate on the "product_name" field.
func ProductNameNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldProductName, vs...))
}

// ProductNameGT applies the GT predicate on the "product_name" field.
func ProductNameGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldProductName, v))
}

// ProductNameGTE applies the GTE predicate on the "product_name" field.
func ProductNameGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldProductName, v))
}

// ProductNameLT applies the LT predicate on the "product_name" field.
func ProductNameLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldProductName, v))
}

// ProductNameLTE applies the LTE predicate on the "product_name" field.
func ProductNameLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldProductName, v))
}

// ProductNameContains applies the Contains predicate on the "product_name" field.
func ProductNameContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldProductName, v))
}

// ProductNameHasPrefix applies the HasPrefix predicate on the "product_name" field.
func ProductNameHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldProductName, v))
}

// ProductNameHasSuffix applies the HasSuffix predicate on the "product_name" field.
func ProductNameHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldProductName, v))
}

// ProductNameEqualFold applies the EqualFold predicate on the "product_name" field.
func ProductNameEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldProductName, v))
}

// ProductNameContainsFold applies the ContainsFold predicate on the "product_name" field.
func ProductNameContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldProductName, v))
}

// ForSaleEQ applies the EQ predicate on the "for_sale" field.
func ForSaleEQ(v bool) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldForSale, v))
}

// ForSaleNEQ applies the NEQ predicate on the "for_sale" field.
func ForSaleNEQ(v bool) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldForSale, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGlobalPlanSubscriptions applies the HasEdge predicate on the "global_plan_subscriptions" edge.
func HasGlobalPlanSubscriptions() predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GlobalPlanSubscriptionsTable, GlobalPlanSubscriptionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGlobalPlanSubscriptionsWith applies the HasEdge predicate on the "global_plan_subscriptions" edge with a given conditions (other predicates).
func HasGlobalPlanSubscriptionsWith(preds ...predicate.UserGlobalPlanSubscription) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(func(s *sql.Selector) {
		step := newGlobalPlanSubscriptionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionPlan) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionPlan) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionPlan) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.NotPredicates(p))
}
