// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/creemproductbinding"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CreemProductBindingDelete is the builder for deleting a CreemProductBinding entity.
type CreemProductBindingDelete struct {
	config
	hooks    []Hook
	mutation *CreemProductBindingMutation
}

// Where appends a list predicates to the CreemProductBindingDelete builder.
func (_d *CreemProductBindingDelete) Where(ps ...predicate.CreemProductBinding) *CreemProductBindingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CreemProductBindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CreemProductBindingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CreemProductBindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(creemproductbinding.Table, sqlgraph.NewFieldSpec(creemproductbinding.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CreemProductBindingDeleteOne is the builder for deleting a single CreemProductBinding entity.
type CreemProductBindingDeleteOne struct {
	_d *CreemProductBindingDelete
}

// Where appends a list predicates to the CreemProductBindingDelete builder.
func (_d *CreemProductBindingDeleteOne) Where(ps ...predicate.CreemProductBinding) *CreemProductBindingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CreemProductBindingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{creemproductbinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CreemProductBindingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
