// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/creemrefundevent"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CreemRefundEventUpdate is the builder for updating CreemRefundEvent entities.
type CreemRefundEventUpdate struct {
	config
	hooks    []Hook
	mutation *CreemRefundEventMutation
}

// Where appends a list predicates to the CreemRefundEventUpdate builder.
func (_u *CreemRefundEventUpdate) Where(ps ...predicate.CreemRefundEvent) *CreemRefundEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *CreemRefundEventUpdate) SetEventID(v string) *CreemRefundEventUpdate {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *CreemRefundEventUpdate) SetNillableEventID(v *string) *CreemRefundEventUpdate {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetProviderRefundID sets the "provider_refund_id" field.
func (_u *CreemRefundEventUpdate) SetProviderRefundID(v string) *CreemRefundEventUpdate {
	_u.mutation.SetProviderRefundID(v)
	return _u
}

// SetNillableProviderRefundID sets the "provider_refund_id" field if the given value is not nil.
func (_u *CreemRefundEventUpdate) SetNillableProviderRefundID(v *string) *CreemRefundEventUpdate {
	if v != nil {
		_u.SetProviderRefundID(*v)
	}
	return _u
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (_u *CreemRefundEventUpdate) SetProviderInstanceID(v int64) *CreemRefundEventUpdate {
	_u.mutation.ResetProviderInstanceID()
	_u.mutation.SetProviderInstanceID(v)
	return _u
}

// SetNillableProviderInstanceID sets the "provider_instance_id" field if the given value is not nil.
func (_u *CreemRefundEventUpdate) SetNillableProviderInstanceID(v *int64) *CreemRefundEventUpdate {
	if v != nil {
		_u.SetProviderInstanceID(*v)
	}
	return _u
}

// AddProviderInstanceID adds value to the "provider_instance_id" field.
func (_u *CreemRefundEventUpdate) AddProviderInstanceID(v int64) *CreemRefundEventUpdate {
	_u.mutation.AddProviderInstanceID(v)
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *CreemRefundEventUpdate) SetPaymentOrderID(v int64) *CreemRefundEventUpdate {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *CreemRefundEventUpdate) SetNillablePaymentOrderID(v *int64) *CreemRefundEventUpdate {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *CreemRefundEventUpdate) AddPaymentOrderID(v int64) *CreemRefundEventUpdate {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (_u *CreemRefundEventUpdate) ClearPaymentOrderID() *CreemRefundEventUpdate {
	_u.mutation.ClearPaymentOrderID()
	return _u
}

// SetTransactionID sets the "transaction_id" field.
func (_u *CreemRefundEventUpdate) SetTransactionID(v string) *CreemRefundEventUpdate {
	_u.mutation.SetTransactionID(v)
	return _u
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (_u *CreemRefundEventUpdate) SetNillableTransactionID(v *string) *CreemRefundEventUpdate {
	if v != nil {
		_u.SetTransactionID(*v)
	}
	return _u
}

// SetRefundAmountMinor sets the "refund_amount_minor" field.
func (_u *CreemRefundEventUpdate) SetRefundAmountMinor(v int64) *CreemRefundEventUpdate {
	_u.mutation.ResetRefundAmountMinor()
	_u.mutation.SetRefundAmountMinor(v)
	return _u
}

// SetNillableRefundAmountMinor sets the "refund_amount_minor" field if the given value is not nil.
func (_u *CreemRefundEventUpdate) SetNillableRefundAmountMinor(v *int64) *CreemRefundEventUpdate {
	if v != nil {
		_u.SetRefundAmountMinor(*v)
	}
	return _u
}

// AddRefundAmountMinor adds value to the "refund_amount_minor" field.
func (_u *CreemRefundEventUpdate) AddRefundAmountMinor(v int64) *CreemRefundEventUpdate {
	_u.mutation.AddRefundAmountMinor(v)
	return _u
}

// SetCumulativeRefundedMinor sets the "cumulative_refunded_minor" field.
func (_u *CreemRefundEventUpdate) SetCumulativeRefundedMinor(v int64) *CreemRefundEventUpdate {
	_u.mutation.ResetCumulativeRefundedMinor()
	_u.mutation.SetCumulativeRefundedMinor(v)
	return _u
}

// SetNillableCumulativeRefundedMinor sets the "cumulative_refunded_minor" field if the given value is not nil.
func (_u *CreemRefundEventUpdate) SetNillableCumulativeRefundedMinor(v *int64) *CreemRefundEventUpdate {
	if v != nil {
		_u.SetCumulativeRefundedMinor(*v)
	}
	return _u
}

// AddCumulativeRefundedMinor adds value to the "cumulative_refunded_minor" field.
func (_u *CreemRefundEventUpdate) AddCumulativeRefundedMinor(v int64) *CreemRefundEventUpdate {
	_u.mutation.AddCumulativeRefundedMinor(v)
	return _u
}

// SetTransactionAmountPaidMinor sets the "transaction_amount_paid_minor" field.
func (_u *CreemRefundEventUpdate) SetTransactionAmountPaidMinor(v int64) *CreemRefundEventUpdate {
	_u.mutation.ResetTransactionAmountPaidMinor()
	_u.mutation.SetTransactionAmountPaidMinor(v)
	return _u
}

// SetNillableTransactionAmountPaidMinor sets the "transaction_amount_paid_minor" field if the given value is not nil.
func (_u *CreemRefundEventUpdate) SetNillableTransactionAmountPaidMinor(v *int64) *CreemRefundEventUpdate {
	if v != nil {
		_u.SetTransactionAmountPaidMinor(*v)
	}
	return _u
}

// AddTransactionAmountPaidMinor adds value to the "transaction_amount_paid_minor" field.
func (_u *CreemRefundEventUpdate) AddTransactionAmountPaidMinor(v int64) *CreemRefundEventUpdate {
	_u.mutation.AddTransactionAmountPaidMinor(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *CreemRefundEventUpdate) SetCurrency(v string) *CreemRefundEventUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *CreemRefundEventUpdate) SetNillableCurrency(v *string) *CreemRefundEventUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetRefundRatio sets the "refund_ratio" field.
func (_u *CreemRefundEventUpdate) SetRefundRatio(v float64) *CreemRefundEventUpdate {
	_u.mutation.ResetRefundRatio()
	_u.mutation.SetRefundRatio(v)
	return _u
}

// SetNillableRefundRatio sets the "refund_ratio" field if the given value is not nil.
func (_u *CreemRefundEventUpdate) SetNillableRefundRatio(v *float64) *CreemRefundEventUpdate {
	if v != nil {
		_u.SetRefundRatio(*v)
	}
	return _u
}

// AddRefundRatio adds value to the "refund_ratio" field.
func (_u *CreemRefundEventUpdate) AddRefundRatio(v float64) *CreemRefundEventUpdate {
	_u.mutation.AddRefundRatio(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CreemRefundEventUpdate) SetStatus(v string) *CreemRefundEventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CreemRefundEventUpdate) SetNillableStatus(v *string) *CreemRefundEventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRecoverySnapshot sets the "recovery_snapshot" field.
func (_u *CreemRefundEventUpdate) SetRecoverySnapshot(v map[string]interface{}) *CreemRefundEventUpdate {
	_u.mutation.SetRecoverySnapshot(v)
	return _u
}

// ClearRecoverySnapshot clears the value of the "recovery_snapshot" field.
func (_u *CreemRefundEventUpdate) ClearRecoverySnapshot() *CreemRefundEventUpdate {
	_u.mutation.ClearRecoverySnapshot()
	return _u
}

// SetRawPayload sets the "raw_payload" field.
func (_u *CreemRefundEventUpdate) SetRawPayload(v map[string]interface{}) *CreemRefundEventUpdate {
	_u.mutation.SetRawPayload(v)
	return _u
}

// ClearRawPayload clears the value of the "raw_payload" field.
func (_u *CreemRefundEventUpdate) ClearRawPayload() *CreemRefundEventUpdate {
	_u.mutation.ClearRawPayload()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *CreemRefundEventUpdate) SetAttempts(v int) *CreemRefundEventUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *CreemRefundEventUpdate) SetNillableAttempts(v *int) *CreemRefundEventUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *CreemRefundEventUpdate) AddAttempts(v int) *CreemRefundEventUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CreemRefundEventUpdate) SetLastError(v string) *CreemRefundEventUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CreemRefundEventUpdate) SetNillableLastError(v *string) *CreemRefundEventUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetProcessedAt sets the "processed_at" field.
func (_u *CreemRefundEventUpdate) SetProcessedAt(v time.Time) *CreemRefundEventUpdate {
	_u.mutation.SetProcessedAt(v)
	return _u
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_u *CreemRefundEventUpdate) SetNillableProcessedAt(v *time.Time) *CreemRefundEventUpdate {
	if v != nil {
		_u.SetProcessedAt(*v)
	}
	return _u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (_u *CreemRefundEventUpdate) ClearProcessedAt() *CreemRefundEventUpdate {
	_u.mutation.ClearProcessedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CreemRefundEventUpdate) SetUpdatedAt(v time.Time) *CreemRefundEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CreemRefundEventMutation object of the builder.
func (_u *CreemRefundEventUpdate) Mutation() *CreemRefundEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CreemRefundEventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CreemRefundEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CreemRefundEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CreemRefundEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CreemRefundEventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := creemrefundevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CreemRefundEventUpdate) check() error {
	if v, ok := _u.mutation.EventID(); ok {
		if err := creemrefundevent.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "CreemRefundEvent.event_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderRefundID(); ok {
		if err := creemrefundevent.ProviderRefundIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_refund_id", err: fmt.Errorf(`ent: validator failed for field "CreemRefundEvent.provider_refund_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TransactionID(); ok {
		if err := creemrefundevent.TransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "transaction_id", err: fmt.Errorf(`ent: validator failed for field "CreemRefundEvent.transaction_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := creemrefundevent.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CreemRefundEvent.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := creemrefundevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CreemRefundEvent.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CreemRefundEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(creemrefundevent.Table, creemrefundevent.Columns, sqlgraph.NewFieldSpec(creemrefundevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(creemrefundevent.FieldEventID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderRefundID(); ok {
		_spec.SetField(creemrefundevent.FieldProviderRefundID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderInstanceID(); ok {
		_spec.SetField(creemrefundevent.FieldProviderInstanceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProviderInstanceID(); ok {
		_spec.AddField(creemrefundevent.FieldProviderInstanceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(creemrefundevent.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(creemrefundevent.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if _u.mutation.PaymentOrderIDCleared() {
		_spec.ClearField(creemrefundevent.FieldPaymentOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.TransactionID(); ok {
		_spec.SetField(creemrefundevent.FieldTransactionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundAmountMinor(); ok {
		_spec.SetField(creemrefundevent.FieldRefundAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefundAmountMinor(); ok {
		_spec.AddField(creemrefundevent.FieldRefundAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CumulativeRefundedMinor(); ok {
		_spec.SetField(creemrefundevent.FieldCumulativeRefundedMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCumulativeRefundedMinor(); ok {
		_spec.AddField(creemrefundevent.FieldCumulativeRefundedMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TransactionAmountPaidMinor(); ok {
		_spec.SetField(creemrefundevent.FieldTransactionAmountPaidMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTransactionAmountPaidMinor(); ok {
		_spec.AddField(creemrefundevent.FieldTransactionAmountPaidMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(creemrefundevent.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundRatio(); ok {
		_spec.SetField(creemrefundevent.FieldRefundRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefundRatio(); ok {
		_spec.AddField(creemrefundevent.FieldRefundRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(creemrefundevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecoverySnapshot(); ok {
		_spec.SetField(creemrefundevent.FieldRecoverySnapshot, field.TypeJSON, value)
	}
	if _u.mutation.RecoverySnapshotCleared() {
		_spec.ClearField(creemrefundevent.FieldRecoverySnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.RawPayload(); ok {
		_spec.SetField(creemrefundevent.FieldRawPayload, field.TypeJSON, value)
	}
	if _u.mutation.RawPayloadCleared() {
		_spec.ClearField(creemrefundevent.FieldRawPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(creemrefundevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(creemrefundevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(creemrefundevent.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcessedAt(); ok {
		_spec.SetField(creemrefundevent.FieldProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessedAtCleared() {
		_spec.ClearField(creemrefundevent.FieldProcessedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(creemrefundevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creemrefundevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CreemRefundEventUpdateOne is the builder for updating a single CreemRefundEvent entity.
type CreemRefundEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CreemRefundEventMutation
}

// SetEventID sets the "event_id" field.
func (_u *CreemRefundEventUpdateOne) SetEventID(v string) *CreemRefundEventUpdateOne {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *CreemRefundEventUpdateOne) SetNillableEventID(v *string) *CreemRefundEventUpdateOne {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetProviderRefundID sets the "provider_refund_id" field.
func (_u *CreemRefundEventUpdateOne) SetProviderRefundID(v string) *CreemRefundEventUpdateOne {
	_u.mutation.SetProviderRefundID(v)
	return _u
}

// SetNillableProviderRefundID sets the "provider_refund_id" field if the given value is not nil.
func (_u *CreemRefundEventUpdateOne) SetNillableProviderRefundID(v *string) *CreemRefundEventUpdateOne {
	if v != nil {
		_u.SetProviderRefundID(*v)
	}
	return _u
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (_u *CreemRefundEventUpdateOne) SetProviderInstanceID(v int64) *CreemRefundEventUpdateOne {
	_u.mutation.ResetProviderInstanceID()
	_u.mutation.SetProviderInstanceID(v)
	return _u
}

// SetNillableProviderInstanceID sets the "provider_instance_id" field if the given value is not nil.
func (_u *CreemRefundEventUpdateOne) SetNillableProviderInstanceID(v *int64) *CreemRefundEventUpdateOne {
	if v != nil {
		_u.SetProviderInstanceID(*v)
	}
	return _u
}

// AddProviderInstanceID adds value to the "provider_instance_id" field.
func (_u *CreemRefundEventUpdateOne) AddProviderInstanceID(v int64) *CreemRefundEventUpdateOne {
	_u.mutation.AddProviderInstanceID(v)
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *CreemRefundEventUpdateOne) SetPaymentOrderID(v int64) *CreemRefundEventUpdateOne {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *CreemRefundEventUpdateOne) SetNillablePaymentOrderID(v *int64) *CreemRefundEventUpdateOne {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *CreemRefundEventUpdateOne) AddPaymentOrderID(v int64) *CreemRefundEventUpdateOne {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (_u *CreemRefundEventUpdateOne) ClearPaymentOrderID() *CreemRefundEventUpdateOne {
	_u.mutation.ClearPaymentOrderID()
	return _u
}

// SetTransactionID sets the "transaction_id" field.
func (_u *CreemRefundEventUpdateOne) SetTransactionID(v string) *CreemRefundEventUpdateOne {
	_u.mutation.SetTransactionID(v)
	return _u
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (_u *CreemRefundEventUpdateOne) SetNillableTransactionID(v *string) *CreemRefundEventUpdateOne {
	if v != nil {
		_u.SetTransactionID(*v)
	}
	return _u
}

// SetRefundAmountMinor sets the "refund_amount_minor" field.
func (_u *CreemRefundEventUpdateOne) SetRefundAmountMinor(v int64) *CreemRefundEventUpdateOne {
	_u.mutation.ResetRefundAmountMinor()
	_u.mutation.SetRefundAmountMinor(v)
	return _u
}

// SetNillableRefundAmountMinor sets the "refund_amount_minor" field if the given value is not nil.
func (_u *CreemRefundEventUpdateOne) SetNillableRefundAmountMinor(v *int64) *CreemRefundEventUpdateOne {
	if v != nil {
		_u.SetRefundAmountMinor(*v)
	}
	return _u
}

// AddRefundAmountMinor adds value to the "refund_amount_minor" field.
func (_u *CreemRefundEventUpdateOne) AddRefundAmountMinor(v int64) *CreemRefundEventUpdateOne {
	_u.mutation.AddRefundAmountMinor(v)
	return _u
}

// SetCumulativeRefundedMinor sets the "cumulative_refunded_minor" field.
func (_u *CreemRefundEventUpdateOne) SetCumulativeRefundedMinor(v int64) *CreemRefundEventUpdateOne {
	_u.mutation.ResetCumulativeRefundedMinor()
	_u.mutation.SetCumulativeRefundedMinor(v)
	return _u
}

// SetNillableCumulativeRefundedMinor sets the "cumulative_refunded_minor" field if the given value is not nil.
func (_u *CreemRefundEventUpdateOne) SetNillableCumulativeRefundedMinor(v *int64) *CreemRefundEventUpdateOne {
	if v != nil {
		_u.SetCumulativeRefundedMinor(*v)
	}
	return _u
}

// AddCumulativeRefundedMinor adds value to the "cumulative_refunded_minor" field.
func (_u *CreemRefundEventUpdateOne) AddCumulativeRefundedMinor(v int64) *CreemRefundEventUpdateOne {
	_u.mutation.AddCumulativeRefundedMinor(v)
	return _u
}

// SetTransactionAmountPaidMinor sets the "transaction_amount_paid_minor" field.
func (_u *CreemRefundEventUpdateOne) SetTransactionAmountPaidMinor(v int64) *CreemRefundEventUpdateOne {
	_u.mutation.ResetTransactionAmountPaidMinor()
	_u.mutation.SetTransactionAmountPaidMinor(v)
	return _u
}

// SetNillableTransactionAmountPaidMinor sets the "transaction_amount_paid_minor" field if the given value is not nil.
func (_u *CreemRefundEventUpdateOne) SetNillableTransactionAmountPaidMinor(v *int64) *CreemRefundEventUpdateOne {
	if v != nil {
		_u.SetTransactionAmountPaidMinor(*v)
	}
	return _u
}

// AddTransactionAmountPaidMinor adds value to the "transaction_amount_paid_minor" field.
func (_u *CreemRefundEventUpdateOne) AddTransactionAmountPaidMinor(v int64) *CreemRefundEventUpdateOne {
	_u.mutation.AddTransactionAmountPaidMinor(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *CreemRefundEventUpdateOne) SetCurrency(v string) *CreemRefundEventUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *CreemRefundEventUpdateOne) SetNillableCurrency(v *string) *CreemRefundEventUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetRefundRatio sets the "refund_ratio" field.
func (_u *CreemRefundEventUpdateOne) SetRefundRatio(v float64) *CreemRefundEventUpdateOne {
	_u.mutation.ResetRefundRatio()
	_u.mutation.SetRefundRatio(v)
	return _u
}

// SetNillableRefundRatio sets the "refund_ratio" field if the given value is not nil.
func (_u *CreemRefundEventUpdateOne) SetNillableRefundRatio(v *float64) *CreemRefundEventUpdateOne {
	if v != nil {
		_u.SetRefundRatio(*v)
	}
	return _u
}

// AddRefundRatio adds value to the "refund_ratio" field.
func (_u *CreemRefundEventUpdateOne) AddRefundRatio(v float64) *CreemRefundEventUpdateOne {
	_u.mutation.AddRefundRatio(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CreemRefundEventUpdateOne) SetStatus(v string) *CreemRefundEventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CreemRefundEventUpdateOne) SetNillableStatus(v *string) *CreemRefundEventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRecoverySnapshot sets the "recovery_snapshot" field.
func (_u *CreemRefundEventUpdateOne) SetRecoverySnapshot(v map[string]interface{}) *CreemRefundEventUpdateOne {
	_u.mutation.SetRecoverySnapshot(v)
	return _u
}

// ClearRecoverySnapshot clears the value of the "recovery_snapshot" field.
func (_u *CreemRefundEventUpdateOne) ClearRecoverySnapshot() *CreemRefundEventUpdateOne {
	_u.mutation.ClearRecoverySnapshot()
	return _u
}

// SetRawPayload sets the "raw_payload" field.
func (_u *CreemRefundEventUpdateOne) SetRawPayload(v map[string]interface{}) *CreemRefundEventUpdateOne {
	_u.mutation.SetRawPayload(v)
	return _u
}

// ClearRawPayload clears the value of the "raw_payload" field.
func (_u *CreemRefundEventUpdateOne) ClearRawPayload() *CreemRefundEventUpdateOne {
	_u.mutation.ClearRawPayload()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *CreemRefundEventUpdateOne) SetAttempts(v int) *CreemRefundEventUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *CreemRefundEventUpdateOne) SetNillableAttempts(v *int) *CreemRefundEventUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *CreemRefundEventUpdateOne) AddAttempts(v int) *CreemRefundEventUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CreemRefundEventUpdateOne) SetLastError(v string) *CreemRefundEventUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CreemRefundEventUpdateOne) SetNillableLastError(v *string) *CreemRefundEventUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetProcessedAt sets the "processed_at" field.
func (_u *CreemRefundEventUpdateOne) SetProcessedAt(v time.Time) *CreemRefundEventUpdateOne {
	_u.mutation.SetProcessedAt(v)
	return _u
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_u *CreemRefundEventUpdateOne) SetNillableProcessedAt(v *time.Time) *CreemRefundEventUpdateOne {
	if v != nil {
		_u.SetProcessedAt(*v)
	}
	return _u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (_u *CreemRefundEventUpdateOne) ClearProcessedAt() *CreemRefundEventUpdateOne {
	_u.mutation.ClearProcessedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CreemRefundEventUpdateOne) SetUpdatedAt(v time.Time) *CreemRefundEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CreemRefundEventMutation object of the builder.
func (_u *CreemRefundEventUpdateOne) Mutation() *CreemRefundEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the CreemRefundEventUpdate builder.
func (_u *CreemRefundEventUpdateOne) Where(ps ...predicate.CreemRefundEvent) *CreemRefundEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CreemRefundEventUpdateOne) Select(field string, fields ...string) *CreemRefundEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CreemRefundEvent entity.
func (_u *CreemRefundEventUpdateOne) Save(ctx context.Context) (*CreemRefundEvent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CreemRefundEventUpdateOne) SaveX(ctx context.Context) *CreemRefundEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CreemRefundEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CreemRefundEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CreemRefundEventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := creemrefundevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CreemRefundEventUpdateOne) check() error {
	if v, ok := _u.mutation.EventID(); ok {
		if err := creemrefundevent.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "CreemRefundEvent.event_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderRefundID(); ok {
		if err := creemrefundevent.ProviderRefundIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_refund_id", err: fmt.Errorf(`ent: validator failed for field "CreemRefundEvent.provider_refund_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TransactionID(); ok {
		if err := creemrefundevent.TransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "transaction_id", err: fmt.Errorf(`ent: validator failed for field "CreemRefundEvent.transaction_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := creemrefundevent.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CreemRefundEvent.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := creemrefundevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CreemRefundEvent.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CreemRefundEventUpdateOne) sqlSave(ctx context.Context) (_node *CreemRefundEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(creemrefundevent.Table, creemrefundevent.Columns, sqlgraph.NewFieldSpec(creemrefundevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CreemRefundEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, creemrefundevent.FieldID)
		for _, f := range fields {
			if !creemrefundevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != creemrefundevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(creemrefundevent.FieldEventID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderRefundID(); ok {
		_spec.SetField(creemrefundevent.FieldProviderRefundID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderInstanceID(); ok {
		_spec.SetField(creemrefundevent.FieldProviderInstanceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProviderInstanceID(); ok {
		_spec.AddField(creemrefundevent.FieldProviderInstanceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(creemrefundevent.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(creemrefundevent.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if _u.mutation.PaymentOrderIDCleared() {
		_spec.ClearField(creemrefundevent.FieldPaymentOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.TransactionID(); ok {
		_spec.SetField(creemrefundevent.FieldTransactionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundAmountMinor(); ok {
		_spec.SetField(creemrefundevent.FieldRefundAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefundAmountMinor(); ok {
		_spec.AddField(creemrefundevent.FieldRefundAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CumulativeRefundedMinor(); ok {
		_spec.SetField(creemrefundevent.FieldCumulativeRefundedMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCumulativeRefundedMinor(); ok {
		_spec.AddField(creemrefundevent.FieldCumulativeRefundedMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TransactionAmountPaidMinor(); ok {
		_spec.SetField(creemrefundevent.FieldTransactionAmountPaidMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTransactionAmountPaidMinor(); ok {
		_spec.AddField(creemrefundevent.FieldTransactionAmountPaidMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(creemrefundevent.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundRatio(); ok {
		_spec.SetField(creemrefundevent.FieldRefundRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefundRatio(); ok {
		_spec.AddField(creemrefundevent.FieldRefundRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(creemrefundevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecoverySnapshot(); ok {
		_spec.SetField(creemrefundevent.FieldRecoverySnapshot, field.TypeJSON, value)
	}
	if _u.mutation.RecoverySnapshotCleared() {
		_spec.ClearField(creemrefundevent.FieldRecoverySnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.RawPayload(); ok {
		_spec.SetField(creemrefundevent.FieldRawPayload, field.TypeJSON, value)
	}
	if _u.mutation.RawPayloadCleared() {
		_spec.ClearField(creemrefundevent.FieldRawPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(creemrefundevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(creemrefundevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(creemrefundevent.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcessedAt(); ok {
		_spec.SetField(creemrefundevent.FieldProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessedAtCleared() {
		_spec.ClearField(creemrefundevent.FieldProcessedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(creemrefundevent.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &CreemRefundEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creemrefundevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
