// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/creemproductbinding"
)

// CreemProductBinding is the model entity for the CreemProductBinding schema.
type CreemProductBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ProviderInstanceID holds the value of the "provider_instance_id" field.
	ProviderInstanceID int64 `json:"provider_instance_id,omitempty"`
	// ExternalProductID holds the value of the "external_product_id" field.
	ExternalProductID string `json:"external_product_id,omitempty"`
	// TargetType holds the value of the "target_type" field.
	TargetType string `json:"target_type,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID *int64 `json:"plan_id,omitempty"`
	// CreditedBalance holds the value of the "credited_balance" field.
	CreditedBalance *float64 `json:"credited_balance,omitempty"`
	// ProductName holds the value of the "product_name" field.
	ProductName string `json:"product_name,omitempty"`
	// PriceMinor holds the value of the "price_minor" field.
	PriceMinor int64 `json:"price_minor,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// BillingType holds the value of the "billing_type" field.
	BillingType string `json:"billing_type,omitempty"`
	// ProductStatus holds the value of the "product_status" field.
	ProductStatus string `json:"product_status,omitempty"`
	// TaxMode holds the value of the "tax_mode" field.
	TaxMode string `json:"tax_mode,omitempty"`
	// Environment holds the value of the "environment" field.
	Environment string `json:"environment,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled"`
	// HealthStatus holds the value of the "health_status" field.
	HealthStatus string `json:"health_status,omitempty"`
	// HealthReason holds the value of the "health_reason" field.
	HealthReason string `json:"health_reason,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// LastSyncedAt holds the value of the "last_synced_at" field.
	LastSyncedAt *time.Time `json:"last_synced_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CreemProductBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case creemproductbinding.FieldEnabled:
			values[i] = new(sql.NullBool)
		case creemproductbinding.FieldCreditedBalance:
			values[i] = new(sql.NullFloat64)
		case creemproductbinding.FieldID, creemproductbinding.FieldProviderInstanceID, creemproductbinding.FieldPlanID, creemproductbinding.FieldPriceMinor, creemproductbinding.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case creemproductbinding.FieldExternalProductID, creemproductbinding.FieldTargetType, creemproductbinding.FieldProductName, creemproductbinding.FieldCurrency, creemproductbinding.FieldBillingType, creemproductbinding.FieldProductStatus, creemproductbinding.FieldTaxMode, creemproductbinding.FieldEnvironment, creemproductbinding.FieldHealthStatus, creemproductbinding.FieldHealthReason:
			values[i] = new(sql.NullString)
		case creemproductbinding.FieldLastSyncedAt, creemproductbinding.FieldCreatedAt, creemproductbinding.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CreemProductBinding fields.
func (_m *CreemProductBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case creemproductbinding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case creemproductbinding.FieldProviderInstanceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_instance_id", values[i])
			} else if value.Valid {
				_m.ProviderInstanceID = value.Int64
			}
		case creemproductbinding.FieldExternalProductID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_product_id", values[i])
			} else if value.Valid {
				_m.ExternalProductID = value.String
			}
		case creemproductbinding.FieldTargetType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_type", values[i])
			} else if value.Valid {
				_m.TargetType = value.String
			}
		case creemproductbinding.FieldPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = new(int64)
				*_m.PlanID = value.Int64
			}
		case creemproductbinding.FieldCreditedBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field credited_balance", values[i])
			} else if value.Valid {
				_m.CreditedBalance = new(float64)
				*_m.CreditedBalance = value.Float64
			}
		case creemproductbinding.FieldProductName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_name", values[i])
			} else if value.Valid {
				_m.ProductName = value.String
			}
		case creemproductbinding.FieldPriceMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_minor", values[i])
			} else if value.Valid {
				_m.PriceMinor = value.Int64
			}
		case creemproductbinding.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case creemproductbinding.FieldBillingType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_type", values[i])
			} else if value.Valid {
				_m.BillingType = value.String
			}
		case creemproductbinding.FieldProductStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_status", values[i])
			} else if value.Valid {
				_m.ProductStatus = value.String
			}
		case creemproductbinding.FieldTaxMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_mode", values[i])
			} else if value.Valid {
				_m.TaxMode = value.String
			}
		case creemproductbinding.FieldEnvironment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment", values[i])
			} else if value.Valid {
				_m.Environment = value.String
			}
		case creemproductbinding.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case creemproductbinding.FieldHealthStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field health_status", values[i])
			} else if value.Valid {
				_m.HealthStatus = value.String
			}
		case creemproductbinding.FieldHealthReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field health_reason", values[i])
			} else if value.Valid {
				_m.HealthReason = value.String
			}
		case creemproductbinding.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case creemproductbinding.FieldLastSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_synced_at", values[i])
			} else if value.Valid {
				_m.LastSyncedAt = new(time.Time)
				*_m.LastSyncedAt = value.Time
			}
		case creemproductbinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case creemproductbinding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CreemProductBinding.
// This includes values selected through modifiers, order, etc.
func (_m *CreemProductBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CreemProductBinding.
// Note that you need to call CreemProductBinding.Unwrap() before calling this method if this CreemProductBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CreemProductBinding) Update() *CreemProductBindingUpdateOne {
	return NewCreemProductBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CreemProductBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CreemProductBinding) Unwrap() *CreemProductBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CreemProductBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CreemProductBinding) String() string {
	var builder strings.Builder
	builder.WriteString("CreemProductBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider_instance_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderInstanceID))
	builder.WriteString(", ")
	builder.WriteString("external_product_id=")
	builder.WriteString(_m.ExternalProductID)
	builder.WriteString(", ")
	builder.WriteString("target_type=")
	builder.WriteString(_m.TargetType)
	builder.WriteString(", ")
	if v := _m.PlanID; v != nil {
		builder.WriteString("plan_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreditedBalance; v != nil {
		builder.WriteString("credited_balance=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("product_name=")
	builder.WriteString(_m.ProductName)
	builder.WriteString(", ")
	builder.WriteString("price_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceMinor))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("billing_type=")
	builder.WriteString(_m.BillingType)
	builder.WriteString(", ")
	builder.WriteString("product_status=")
	builder.WriteString(_m.ProductStatus)
	builder.WriteString(", ")
	builder.WriteString("tax_mode=")
	builder.WriteString(_m.TaxMode)
	builder.WriteString(", ")
	builder.WriteString("environment=")
	builder.WriteString(_m.Environment)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("health_status=")
	builder.WriteString(_m.HealthStatus)
	builder.WriteString(", ")
	builder.WriteString("health_reason=")
	builder.WriteString(_m.HealthReason)
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	if v := _m.LastSyncedAt; v != nil {
		builder.WriteString("last_synced_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CreemProductBindings is a parsable slice of CreemProductBinding.
type CreemProductBindings []*CreemProductBinding
