// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/creemrefundevent"
)

// CreemRefundEvent is the model entity for the CreemRefundEvent schema.
type CreemRefundEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// EventID holds the value of the "event_id" field.
	EventID string `json:"event_id,omitempty"`
	// ProviderRefundID holds the value of the "provider_refund_id" field.
	ProviderRefundID string `json:"provider_refund_id,omitempty"`
	// ProviderInstanceID holds the value of the "provider_instance_id" field.
	ProviderInstanceID int64 `json:"provider_instance_id,omitempty"`
	// PaymentOrderID holds the value of the "payment_order_id" field.
	PaymentOrderID *int64 `json:"payment_order_id,omitempty"`
	// TransactionID holds the value of the "transaction_id" field.
	TransactionID string `json:"transaction_id,omitempty"`
	// RefundAmountMinor holds the value of the "refund_amount_minor" field.
	RefundAmountMinor int64 `json:"refund_amount_minor,omitempty"`
	// CumulativeRefundedMinor holds the value of the "cumulative_refunded_minor" field.
	CumulativeRefundedMinor int64 `json:"cumulative_refunded_minor,omitempty"`
	// TransactionAmountPaidMinor holds the value of the "transaction_amount_paid_minor" field.
	TransactionAmountPaidMinor int64 `json:"transaction_amount_paid_minor,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// RefundRatio holds the value of the "refund_ratio" field.
	RefundRatio float64 `json:"refund_ratio,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// RecoverySnapshot holds the value of the "recovery_snapshot" field.
	RecoverySnapshot map[string]interface{} `json:"recovery_snapshot,omitempty"`
	// RawPayload holds the value of the "raw_payload" field.
	RawPayload map[string]interface{} `json:"raw_payload,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// ProcessedAt holds the value of the "processed_at" field.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CreemRefundEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case creemrefundevent.FieldRecoverySnapshot, creemrefundevent.FieldRawPayload:
			values[i] = new([]byte)
		case creemrefundevent.FieldRefundRatio:
			values[i] = new(sql.NullFloat64)
		case creemrefundevent.FieldID, creemrefundevent.FieldProviderInstanceID, creemrefundevent.FieldPaymentOrderID, creemrefundevent.FieldRefundAmountMinor, creemrefundevent.FieldCumulativeRefundedMinor, creemrefundevent.FieldTransactionAmountPaidMinor, creemrefundevent.FieldAttempts:
			values[i] = new(sql.NullInt64)
		case creemrefundevent.FieldEventID, creemrefundevent.FieldProviderRefundID, creemrefundevent.FieldTransactionID, creemrefundevent.FieldCurrency, creemrefundevent.FieldStatus, creemrefundevent.FieldLastError:
			values[i] = new(sql.NullString)
		case creemrefundevent.FieldProcessedAt, creemrefundevent.FieldCreatedAt, creemrefundevent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CreemRefundEvent fields.
func (_m *CreemRefundEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case creemrefundevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case creemrefundevent.FieldEventID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_id", values[i])
			} else if value.Valid {
				_m.EventID = value.String
			}
		case creemrefundevent.FieldProviderRefundID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_refund_id", values[i])
			} else if value.Valid {
				_m.ProviderRefundID = value.String
			}
		case creemrefundevent.FieldProviderInstanceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_instance_id", values[i])
			} else if value.Valid {
				_m.ProviderInstanceID = value.Int64
			}
		case creemrefundevent.FieldPaymentOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_id", values[i])
			} else if value.Valid {
				_m.PaymentOrderID = new(int64)
				*_m.PaymentOrderID = value.Int64
			}
		case creemrefundevent.FieldTransactionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_id", values[i])
			} else if value.Valid {
				_m.TransactionID = value.String
			}
		case creemrefundevent.FieldRefundAmountMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refund_amount_minor", values[i])
			} else if value.Valid {
				_m.RefundAmountMinor = value.Int64
			}
		case creemrefundevent.FieldCumulativeRefundedMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cumulative_refunded_minor", values[i])
			} else if value.Valid {
				_m.CumulativeRefundedMinor = value.Int64
			}
		case creemrefundevent.FieldTransactionAmountPaidMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_amount_paid_minor", values[i])
			} else if value.Valid {
				_m.TransactionAmountPaidMinor = value.Int64
			}
		case creemrefundevent.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case creemrefundevent.FieldRefundRatio:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field refund_ratio", values[i])
			} else if value.Valid {
				_m.RefundRatio = value.Float64
			}
		case creemrefundevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case creemrefundevent.FieldRecoverySnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field recovery_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RecoverySnapshot); err != nil {
					return fmt.Errorf("unmarshal field recovery_snapshot: %w", err)
				}
			}
		case creemrefundevent.FieldRawPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field raw_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RawPayload); err != nil {
					return fmt.Errorf("unmarshal field raw_payload: %w", err)
				}
			}
		case creemrefundevent.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				_m.Attempts = int(value.Int64)
			}
		case creemrefundevent.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case creemrefundevent.FieldProcessedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field processed_at", values[i])
			} else if value.Valid {
				_m.ProcessedAt = new(time.Time)
				*_m.ProcessedAt = value.Time
			}
		case creemrefundevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case creemrefundevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CreemRefundEvent.
// This includes values selected through modifiers, order, etc.
func (_m *CreemRefundEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CreemRefundEvent.
// Note that you need to call CreemRefundEvent.Unwrap() before calling this method if this CreemRefundEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CreemRefundEvent) Update() *CreemRefundEventUpdateOne {
	return NewCreemRefundEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CreemRefundEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CreemRefundEvent) Unwrap() *CreemRefundEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CreemRefundEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CreemRefundEvent) String() string {
	var builder strings.Builder
	builder.WriteString("CreemRefundEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_id=")
	builder.WriteString(_m.EventID)
	builder.WriteString(", ")
	builder.WriteString("provider_refund_id=")
	builder.WriteString(_m.ProviderRefundID)
	builder.WriteString(", ")
	builder.WriteString("provider_instance_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderInstanceID))
	builder.WriteString(", ")
	if v := _m.PaymentOrderID; v != nil {
		builder.WriteString("payment_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("transaction_id=")
	builder.WriteString(_m.TransactionID)
	builder.WriteString(", ")
	builder.WriteString("refund_amount_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundAmountMinor))
	builder.WriteString(", ")
	builder.WriteString("cumulative_refunded_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.CumulativeRefundedMinor))
	builder.WriteString(", ")
	builder.WriteString("transaction_amount_paid_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.TransactionAmountPaidMinor))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("refund_ratio=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundRatio))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("recovery_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecoverySnapshot))
	builder.WriteString(", ")
	builder.WriteString("raw_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.RawPayload))
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	if v := _m.ProcessedAt; v != nil {
		builder.WriteString("processed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CreemRefundEvents is a parsable slice of CreemRefundEvent.
type CreemRefundEvents []*CreemRefundEvent
