// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/creemproductbinding"
)

// CreemProductBindingCreate is the builder for creating a CreemProductBinding entity.
type CreemProductBindingCreate struct {
	config
	mutation *CreemProductBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (_c *CreemProductBindingCreate) SetProviderInstanceID(v int64) *CreemProductBindingCreate {
	_c.mutation.SetProviderInstanceID(v)
	return _c
}

// SetExternalProductID sets the "external_product_id" field.
func (_c *CreemProductBindingCreate) SetExternalProductID(v string) *CreemProductBindingCreate {
	_c.mutation.SetExternalProductID(v)
	return _c
}

// SetTargetType sets the "target_type" field.
func (_c *CreemProductBindingCreate) SetTargetType(v string) *CreemProductBindingCreate {
	_c.mutation.SetTargetType(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *CreemProductBindingCreate) SetPlanID(v int64) *CreemProductBindingCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_c *CreemProductBindingCreate) SetNillablePlanID(v *int64) *CreemProductBindingCreate {
	if v != nil {
		_c.SetPlanID(*v)
	}
	return _c
}

// SetCreditedBalance sets the "credited_balance" field.
func (_c *CreemProductBindingCreate) SetCreditedBalance(v float64) *CreemProductBindingCreate {
	_c.mutation.SetCreditedBalance(v)
	return _c
}

// SetNillableCreditedBalance sets the "credited_balance" field if the given value is not nil.
func (_c *CreemProductBindingCreate) SetNillableCreditedBalance(v *float64) *CreemProductBindingCreate {
	if v != nil {
		_c.SetCreditedBalance(*v)
	}
	return _c
}

// SetProductName sets the "product_name" field.
func (_c *CreemProductBindingCreate) SetProductName(v string) *CreemProductBindingCreate {
	_c.mutation.SetProductName(v)
	return _c
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_c *CreemProductBindingCreate) SetNillableProductName(v *string) *CreemProductBindingCreate {
	if v != nil {
		_c.SetProductName(*v)
	}
	return _c
}

// SetPriceMinor sets the "price_minor" field.
func (_c *CreemProductBindingCreate) SetPriceMinor(v int64) *CreemProductBindingCreate {
	_c.mutation.SetPriceMinor(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *CreemProductBindingCreate) SetCurrency(v string) *CreemProductBindingCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetBillingType sets the "billing_type" field.
func (_c *CreemProductBindingCreate) SetBillingType(v string) *CreemProductBindingCreate {
	_c.mutation.SetBillingType(v)
	return _c
}

// SetNillableBillingType sets the "billing_type" field if the given value is not nil.
func (_c *CreemProductBindingCreate) SetNillableBillingType(v *string) *CreemProductBindingCreate {
	if v != nil {
		_c.SetBillingType(*v)
	}
	return _c
}

// SetProductStatus sets the "product_status" field.
func (_c *CreemProductBindingCreate) SetProductStatus(v string) *CreemProductBindingCreate {
	_c.mutation.SetProductStatus(v)
	return _c
}

// SetNillableProductStatus sets the "product_status" field if the given value is not nil.
func (_c *CreemProductBindingCreate) SetNillableProductStatus(v *string) *CreemProductBindingCreate {
	if v != nil {
		_c.SetProductStatus(*v)
	}
	return _c
}

// SetTaxMode sets the "tax_mode" field.
func (_c *CreemProductBindingCreate) SetTaxMode(v string) *CreemProductBindingCreate {
	_c.mutation.SetTaxMode(v)
	return _c
}

// SetNillableTaxMode sets the "tax_mode" field if the given value is not nil.
func (_c *CreemProductBindingCreate) SetNillableTaxMode(v *string) *CreemProductBindingCreate {
	if v != nil {
		_c.SetTaxMode(*v)
	}
	return _c
}

// SetEnvironment sets the "environment" field.
func (_c *CreemProductBindingCreate) SetEnvironment(v string) *CreemProductBindingCreate {
	_c.mutation.SetEnvironment(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *CreemProductBindingCreate) SetEnabled(v bool) *CreemProductBindingCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *CreemProductBindingCreate) SetNillableEnabled(v *bool) *CreemProductBindingCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetHealthStatus sets the "health_status" field.
func (_c *CreemProductBindingCreate) SetHealthStatus(v string) *CreemProductBindingCreate {
	_c.mutation.SetHealthStatus(v)
	return _c
}

// SetNillableHealthStatus sets the "health_status" field if the given value is not nil.
func (_c *CreemProductBindingCreate) SetNillableHealthStatus(v *string) *CreemProductBindingCreate {
	if v != nil {
		_c.SetHealthStatus(*v)
	}
	return _c
}

// SetHealthReason sets the "health_reason" field.
func (_c *CreemProductBindingCreate) SetHealthReason(v string) *CreemProductBindingCreate {
	_c.mutation.SetHealthReason(v)
	return _c
}

// SetNillableHealthReason sets the "health_reason" field if the given value is not nil.
func (_c *CreemProductBindingCreate) SetNillableHealthReason(v *string) *CreemProductBindingCreate {
	if v != nil {
		_c.SetHealthReason(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *CreemProductBindingCreate) SetSortOrder(v int) *CreemProductBindingCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *CreemProductBindingCreate) SetNillableSortOrder(v *int) *CreemProductBindingCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *CreemProductBindingCreate) SetLastSyncedAt(v time.Time) *CreemProductBindingCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_c *CreemProductBindingCreate) SetNillableLastSyncedAt(v *time.Time) *CreemProductBindingCreate {
	if v != nil {
		_c.SetLastSyncedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CreemProductBindingCreate) SetCreatedAt(v time.Time) *CreemProductBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CreemProductBindingCreate) SetNillableCreatedAt(v *time.Time) *CreemProductBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CreemProductBindingCreate) SetUpdatedAt(v time.Time) *CreemProductBindingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CreemProductBindingCreate) SetNillableUpdatedAt(v *time.Time) *CreemProductBindingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CreemProductBindingMutation object of the builder.
func (_c *CreemProductBindingCreate) Mutation() *CreemProductBindingMutation {
	return _c.mutation
}

// Save creates the CreemProductBinding in the database.
func (_c *CreemProductBindingCreate) Save(ctx context.Context) (*CreemProductBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CreemProductBindingCreate) SaveX(ctx context.Context) *CreemProductBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreemProductBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreemProductBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CreemProductBindingCreate) defaults() {
	if _, ok := _c.mutation.ProductName(); !ok {
		v := creemproductbinding.DefaultProductName
		_c.mutation.SetProductName(v)
	}
	if _, ok := _c.mutation.BillingType(); !ok {
		v := creemproductbinding.DefaultBillingType
		_c.mutation.SetBillingType(v)
	}
	if _, ok := _c.mutation.ProductStatus(); !ok {
		v := creemproductbinding.DefaultProductStatus
		_c.mutation.SetProductStatus(v)
	}
	if _, ok := _c.mutation.TaxMode(); !ok {
		v := creemproductbinding.DefaultTaxMode
		_c.mutation.SetTaxMode(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := creemproductbinding.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.HealthStatus(); !ok {
		v := creemproductbinding.DefaultHealthStatus
		_c.mutation.SetHealthStatus(v)
	}
	if _, ok := _c.mutation.HealthReason(); !ok {
		v := creemproductbinding.DefaultHealthReason
		_c.mutation.SetHealthReason(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := creemproductbinding.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := creemproductbinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := creemproductbinding.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CreemProductBindingCreate) check() error {
	if _, ok := _c.mutation.ProviderInstanceID(); !ok {
		return &ValidationError{Name: "provider_instance_id", err: errors.New(`ent: missing required field "CreemProductBinding.provider_instance_id"`)}
	}
	if _, ok := _c.mutation.ExternalProductID(); !ok {
		return &ValidationError{Name: "external_product_id", err: errors.New(`ent: missing required field "CreemProductBinding.external_product_id"`)}
	}
	if v, ok := _c.mutation.ExternalProductID(); ok {
		if err := creemproductbinding.ExternalProductIDValidator(v); err != nil {
			return &ValidationError{Name: "external_product_id", err: fmt.Errorf(`ent: validator failed for field "CreemProductBinding.external_product_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetType(); !ok {
		return &ValidationError{Name: "target_type", err: errors.New(`ent: missing required field "CreemProductBinding.target_type"`)}
	}
	if v, ok := _c.mutation.TargetType(); ok {
		if err := creemproductbinding.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "CreemProductBinding.target_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProductName(); !ok {
		return &ValidationError{Name: "product_name", err: errors.New(`ent: missing required field "CreemProductBinding.product_name"`)}
	}
	if v, ok := _c.mutation.ProductName(); ok {
		if err := creemproductbinding.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "CreemProductBinding.product_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PriceMinor(); !ok {
		return &ValidationError{Name: "price_minor", err: errors.New(`ent: missing required field "CreemProductBinding.price_minor"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "CreemProductBinding.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := creemproductbinding.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CreemProductBinding.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BillingType(); !ok {
		return &ValidationError{Name: "billing_type", err: errors.New(`ent: missing required field "CreemProductBinding.billing_type"`)}
	}
	if v, ok := _c.mutation.BillingType(); ok {
		if err := creemproductbinding.BillingTypeValidator(v); err != nil {
			return &ValidationError{Name: "billing_type", err: fmt.Errorf(`ent: validator failed for field "CreemProductBinding.billing_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProductStatus(); !ok {
		return &ValidationError{Name: "product_status", err: errors.New(`ent: missing required field "CreemProductBinding.product_status"`)}
	}
	if v, ok := _c.mutation.ProductStatus(); ok {
		if err := creemproductbinding.ProductStatusValidator(v); err != nil {
			return &ValidationError{Name: "product_status", err: fmt.Errorf(`ent: validator failed for field "CreemProductBinding.product_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaxMode(); !ok {
		return &ValidationError{Name: "tax_mode", err: errors.New(`ent: missing required field "CreemProductBinding.tax_mode"`)}
	}
	if v, ok := _c.mutation.TaxMode(); ok {
		if err := creemproductbinding.TaxModeValidator(v); err != nil {
			return &ValidationError{Name: "tax_mode", err: fmt.Errorf(`ent: validator failed for field "CreemProductBinding.tax_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Environment(); !ok {
		return &ValidationError{Name: "environment", err: errors.New(`ent: missing required field "CreemProductBinding.environment"`)}
	}
	if v, ok := _c.mutation.Environment(); ok {
		if err := creemproductbinding.EnvironmentValidator(v); err != nil {
			return &ValidationError{Name: "environment", err: fmt.Errorf(`ent: validator failed for field "CreemProductBinding.environment": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "CreemProductBinding.enabled"`)}
	}
	if _, ok := _c.mutation.HealthStatus(); !ok {
		return &ValidationError{Name: "health_status", err: errors.New(`ent: missing required field "CreemProductBinding.health_status"`)}
	}
	if v, ok := _c.mutation.HealthStatus(); ok {
		if err := creemproductbinding.HealthStatusValidator(v); err != nil {
			return &ValidationError{Name: "health_status", err: fmt.Errorf(`ent: validator failed for field "CreemProductBinding.health_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HealthReason(); !ok {
		return &ValidationError{Name: "health_reason", err: errors.New(`ent: missing required field "CreemProductBinding.health_reason"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "CreemProductBinding.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CreemProductBinding.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CreemProductBinding.updated_at"`)}
	}
	return nil
}

func (_c *CreemProductBindingCreate) sqlSave(ctx context.Context) (*CreemProductBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CreemProductBindingCreate) createSpec() (*CreemProductBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &CreemProductBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(creemproductbinding.Table, sqlgraph.NewFieldSpec(creemproductbinding.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ProviderInstanceID(); ok {
		_spec.SetField(creemproductbinding.FieldProviderInstanceID, field.TypeInt64, value)
		_node.ProviderInstanceID = value
	}
	if value, ok := _c.mutation.ExternalProductID(); ok {
		_spec.SetField(creemproductbinding.FieldExternalProductID, field.TypeString, value)
		_node.ExternalProductID = value
	}
	if value, ok := _c.mutation.TargetType(); ok {
		_spec.SetField(creemproductbinding.FieldTargetType, field.TypeString, value)
		_node.TargetType = value
	}
	if value, ok := _c.mutation.PlanID(); ok {
		_spec.SetField(creemproductbinding.FieldPlanID, field.TypeInt64, value)
		_node.PlanID = &value
	}
	if value, ok := _c.mutation.CreditedBalance(); ok {
		_spec.SetField(creemproductbinding.FieldCreditedBalance, field.TypeFloat64, value)
		_node.CreditedBalance = &value
	}
	if value, ok := _c.mutation.ProductName(); ok {
		_spec.SetField(creemproductbinding.FieldProductName, field.TypeString, value)
		_node.ProductName = value
	}
	if value, ok := _c.mutation.PriceMinor(); ok {
		_spec.SetField(creemproductbinding.FieldPriceMinor, field.TypeInt64, value)
		_node.PriceMinor = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(creemproductbinding.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.BillingType(); ok {
		_spec.SetField(creemproductbinding.FieldBillingType, field.TypeString, value)
		_node.BillingType = value
	}
	if value, ok := _c.mutation.ProductStatus(); ok {
		_spec.SetField(creemproductbinding.FieldProductStatus, field.TypeString, value)
		_node.ProductStatus = value
	}
	if value, ok := _c.mutation.TaxMode(); ok {
		_spec.SetField(creemproductbinding.FieldTaxMode, field.TypeString, value)
		_node.TaxMode = value
	}
	if value, ok := _c.mutation.Environment(); ok {
		_spec.SetField(creemproductbinding.FieldEnvironment, field.TypeString, value)
		_node.Environment = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(creemproductbinding.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.HealthStatus(); ok {
		_spec.SetField(creemproductbinding.FieldHealthStatus, field.TypeString, value)
		_node.HealthStatus = value
	}
	if value, ok := _c.mutation.HealthReason(); ok {
		_spec.SetField(creemproductbinding.FieldHealthReason, field.TypeString, value)
		_node.HealthReason = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(creemproductbinding.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(creemproductbinding.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(creemproductbinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(creemproductbinding.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreemProductBinding.Create().
//		SetProviderInstanceID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreemProductBindingUpsert) {
//			SetProviderInstanceID(v+v).
//		}).
//		Exec(ctx)
func (_c *CreemProductBindingCreate) OnConflict(opts ...sql.ConflictOption) *CreemProductBindingUpsertOne {
	_c.conflict = opts
	return &CreemProductBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreemProductBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreemProductBindingCreate) OnConflictColumns(columns ...string) *CreemProductBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreemProductBindingUpsertOne{
		create: _c,
	}
}

type (
	// CreemProductBindingUpsertOne is the builder for "upsert"-ing
	//  one CreemProductBinding node.
	CreemProductBindingUpsertOne struct {
		create *CreemProductBindingCreate
	}

	// CreemProductBindingUpsert is the "OnConflict" setter.
	CreemProductBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetProviderInstanceID sets the "provider_instance_id" field.
func (u *CreemProductBindingUpsert) SetProviderInstanceID(v int64) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldProviderInstanceID, v)
	return u
}

// UpdateProviderInstanceID sets the "provider_instance_id" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateProviderInstanceID() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldProviderInstanceID)
	return u
}

// AddProviderInstanceID adds v to the "provider_instance_id" field.
func (u *CreemProductBindingUpsert) AddProviderInstanceID(v int64) *CreemProductBindingUpsert {
	u.Add(creemproductbinding.FieldProviderInstanceID, v)
	return u
}

// SetExternalProductID sets the "external_product_id" field.
func (u *CreemProductBindingUpsert) SetExternalProductID(v string) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldExternalProductID, v)
	return u
}

// UpdateExternalProductID sets the "external_product_id" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateExternalProductID() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldExternalProductID)
	return u
}

// SetTargetType sets the "target_type" field.
func (u *CreemProductBindingUpsert) SetTargetType(v string) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldTargetType, v)
	return u
}

// UpdateTargetType sets the "target_type" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateTargetType() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldTargetType)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *CreemProductBindingUpsert) SetPlanID(v int64) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdatePlanID() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldPlanID)
	return u
}

// AddPlanID adds v to the "plan_id" field.
func (u *CreemProductBindingUpsert) AddPlanID(v int64) *CreemProductBindingUpsert {
	u.Add(creemproductbinding.FieldPlanID, v)
	return u
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *CreemProductBindingUpsert) ClearPlanID() *CreemProductBindingUpsert {
	u.SetNull(creemproductbinding.FieldPlanID)
	return u
}

// SetCreditedBalance sets the "credited_balance" field.
func (u *CreemProductBindingUpsert) SetCreditedBalance(v float64) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldCreditedBalance, v)
	return u
}

// UpdateCreditedBalance sets the "credited_balance" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateCreditedBalance() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldCreditedBalance)
	return u
}

// AddCreditedBalance adds v to the "credited_balance" field.
func (u *CreemProductBindingUpsert) AddCreditedBalance(v float64) *CreemProductBindingUpsert {
	u.Add(creemproductbinding.FieldCreditedBalance, v)
	return u
}

// ClearCreditedBalance clears the value of the "credited_balance" field.
func (u *CreemProductBindingUpsert) ClearCreditedBalance() *CreemProductBindingUpsert {
	u.SetNull(creemproductbinding.FieldCreditedBalance)
	return u
}

// SetProductName sets the "product_name" field.
func (u *CreemProductBindingUpsert) SetProductName(v string) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldProductName, v)
	return u
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateProductName() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldProductName)
	return u
}

// SetPriceMinor sets the "price_minor" field.
func (u *CreemProductBindingUpsert) SetPriceMinor(v int64) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldPriceMinor, v)
	return u
}

// UpdatePriceMinor sets the "price_minor" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdatePriceMinor() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldPriceMinor)
	return u
}

// AddPriceMinor adds v to the "price_minor" field.
func (u *CreemProductBindingUpsert) AddPriceMinor(v int64) *CreemProductBindingUpsert {
	u.Add(creemproductbinding.FieldPriceMinor, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *CreemProductBindingUpsert) SetCurrency(v string) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateCurrency() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldCurrency)
	return u
}

// SetBillingType sets the "billing_type" field.
func (u *CreemProductBindingUpsert) SetBillingType(v string) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldBillingType, v)
	return u
}

// UpdateBillingType sets the "billing_type" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateBillingType() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldBillingType)
	return u
}

// SetProductStatus sets the "product_status" field.
func (u *CreemProductBindingUpsert) SetProductStatus(v string) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldProductStatus, v)
	return u
}

// UpdateProductStatus sets the "product_status" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateProductStatus() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldProductStatus)
	return u
}

// SetTaxMode sets the "tax_mode" field.
func (u *CreemProductBindingUpsert) SetTaxMode(v string) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldTaxMode, v)
	return u
}

// UpdateTaxMode sets the "tax_mode" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateTaxMode() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldTaxMode)
	return u
}

// SetEnvironment sets the "environment" field.
func (u *CreemProductBindingUpsert) SetEnvironment(v string) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldEnvironment, v)
	return u
}

// UpdateEnvironment sets the "environment" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateEnvironment() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldEnvironment)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *CreemProductBindingUpsert) SetEnabled(v bool) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateEnabled() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldEnabled)
	return u
}

// SetHealthStatus sets the "health_status" field.
func (u *CreemProductBindingUpsert) SetHealthStatus(v string) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldHealthStatus, v)
	return u
}

// UpdateHealthStatus sets the "health_status" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateHealthStatus() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldHealthStatus)
	return u
}

// SetHealthReason sets the "health_reason" field.
func (u *CreemProductBindingUpsert) SetHealthReason(v string) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldHealthReason, v)
	return u
}

// UpdateHealthReason sets the "health_reason" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateHealthReason() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldHealthReason)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *CreemProductBindingUpsert) SetSortOrder(v int) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateSortOrder() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CreemProductBindingUpsert) AddSortOrder(v int) *CreemProductBindingUpsert {
	u.Add(creemproductbinding.FieldSortOrder, v)
	return u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *CreemProductBindingUpsert) SetLastSyncedAt(v time.Time) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldLastSyncedAt, v)
	return u
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateLastSyncedAt() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldLastSyncedAt)
	return u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *CreemProductBindingUpsert) ClearLastSyncedAt() *CreemProductBindingUpsert {
	u.SetNull(creemproductbinding.FieldLastSyncedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CreemProductBindingUpsert) SetUpdatedAt(v time.Time) *CreemProductBindingUpsert {
	u.Set(creemproductbinding.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreemProductBindingUpsert) UpdateUpdatedAt() *CreemProductBindingUpsert {
	u.SetExcluded(creemproductbinding.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CreemProductBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CreemProductBindingUpsertOne) UpdateNewValues() *CreemProductBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(creemproductbinding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreemProductBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CreemProductBindingUpsertOne) Ignore() *CreemProductBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreemProductBindingUpsertOne) DoNothing() *CreemProductBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreemProductBindingCreate.OnConflict
// documentation for more info.
func (u *CreemProductBindingUpsertOne) Update(set func(*CreemProductBindingUpsert)) *CreemProductBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreemProductBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (u *CreemProductBindingUpsertOne) SetProviderInstanceID(v int64) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetProviderInstanceID(v)
	})
}

// AddProviderInstanceID adds v to the "provider_instance_id" field.
func (u *CreemProductBindingUpsertOne) AddProviderInstanceID(v int64) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.AddProviderInstanceID(v)
	})
}

// UpdateProviderInstanceID sets the "provider_instance_id" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateProviderInstanceID() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateProviderInstanceID()
	})
}

// SetExternalProductID sets the "external_product_id" field.
func (u *CreemProductBindingUpsertOne) SetExternalProductID(v string) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetExternalProductID(v)
	})
}

// UpdateExternalProductID sets the "external_product_id" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateExternalProductID() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateExternalProductID()
	})
}

// SetTargetType sets the "target_type" field.
func (u *CreemProductBindingUpsertOne) SetTargetType(v string) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetTargetType(v)
	})
}

// UpdateTargetType sets the "target_type" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateTargetType() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateTargetType()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *CreemProductBindingUpsertOne) SetPlanID(v int64) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *CreemProductBindingUpsertOne) AddPlanID(v int64) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdatePlanID() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdatePlanID()
	})
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *CreemProductBindingUpsertOne) ClearPlanID() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.ClearPlanID()
	})
}

// SetCreditedBalance sets the "credited_balance" field.
func (u *CreemProductBindingUpsertOne) SetCreditedBalance(v float64) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetCreditedBalance(v)
	})
}

// AddCreditedBalance adds v to the "credited_balance" field.
func (u *CreemProductBindingUpsertOne) AddCreditedBalance(v float64) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.AddCreditedBalance(v)
	})
}

// UpdateCreditedBalance sets the "credited_balance" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateCreditedBalance() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateCreditedBalance()
	})
}

// ClearCreditedBalance clears the value of the "credited_balance" field.
func (u *CreemProductBindingUpsertOne) ClearCreditedBalance() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.ClearCreditedBalance()
	})
}

// SetProductName sets the "product_name" field.
func (u *CreemProductBindingUpsertOne) SetProductName(v string) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetProductName(v)
	})
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateProductName() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateProductName()
	})
}

// SetPriceMinor sets the "price_minor" field.
func (u *CreemProductBindingUpsertOne) SetPriceMinor(v int64) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetPriceMinor(v)
	})
}

// AddPriceMinor adds v to the "price_minor" field.
func (u *CreemProductBindingUpsertOne) AddPriceMinor(v int64) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.AddPriceMinor(v)
	})
}

// UpdatePriceMinor sets the "price_minor" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdatePriceMinor() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdatePriceMinor()
	})
}

// SetCurrency sets the "currency" field.
func (u *CreemProductBindingUpsertOne) SetCurrency(v string) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateCurrency() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateCurrency()
	})
}

// SetBillingType sets the "billing_type" field.
func (u *CreemProductBindingUpsertOne) SetBillingType(v string) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetBillingType(v)
	})
}

// UpdateBillingType sets the "billing_type" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateBillingType() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateBillingType()
	})
}

// SetProductStatus sets the "product_status" field.
func (u *CreemProductBindingUpsertOne) SetProductStatus(v string) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetProductStatus(v)
	})
}

// UpdateProductStatus sets the "product_status" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateProductStatus() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateProductStatus()
	})
}

// SetTaxMode sets the "tax_mode" field.
func (u *CreemProductBindingUpsertOne) SetTaxMode(v string) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetTaxMode(v)
	})
}

// UpdateTaxMode sets the "tax_mode" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateTaxMode() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateTaxMode()
	})
}

// SetEnvironment sets the "environment" field.
func (u *CreemProductBindingUpsertOne) SetEnvironment(v string) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetEnvironment(v)
	})
}

// UpdateEnvironment sets the "environment" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateEnvironment() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateEnvironment()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CreemProductBindingUpsertOne) SetEnabled(v bool) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateEnabled() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateEnabled()
	})
}

// SetHealthStatus sets the "health_status" field.
func (u *CreemProductBindingUpsertOne) SetHealthStatus(v string) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetHealthStatus(v)
	})
}

// UpdateHealthStatus sets the "health_status" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateHealthStatus() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateHealthStatus()
	})
}

// SetHealthReason sets the "health_reason" field.
func (u *CreemProductBindingUpsertOne) SetHealthReason(v string) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetHealthReason(v)
	})
}

// UpdateHealthReason sets the "health_reason" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateHealthReason() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateHealthReason()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CreemProductBindingUpsertOne) SetSortOrder(v int) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CreemProductBindingUpsertOne) AddSortOrder(v int) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateSortOrder() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateSortOrder()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *CreemProductBindingUpsertOne) SetLastSyncedAt(v time.Time) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateLastSyncedAt() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *CreemProductBindingUpsertOne) ClearLastSyncedAt() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.ClearLastSyncedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CreemProductBindingUpsertOne) SetUpdatedAt(v time.Time) *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreemProductBindingUpsertOne) UpdateUpdatedAt() *CreemProductBindingUpsertOne {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CreemProductBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreemProductBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreemProductBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CreemProductBindingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CreemProductBindingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CreemProductBindingCreateBulk is the builder for creating many CreemProductBinding entities in bulk.
type CreemProductBindingCreateBulk struct {
	config
	err      error
	builders []*CreemProductBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the CreemProductBinding entities in the database.
func (_c *CreemProductBindingCreateBulk) Save(ctx context.Context) ([]*CreemProductBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CreemProductBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CreemProductBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CreemProductBindingCreateBulk) SaveX(ctx context.Context) []*CreemProductBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreemProductBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreemProductBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreemProductBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreemProductBindingUpsert) {
//			SetProviderInstanceID(v+v).
//		}).
//		Exec(ctx)
func (_c *CreemProductBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *CreemProductBindingUpsertBulk {
	_c.conflict = opts
	return &CreemProductBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreemProductBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreemProductBindingCreateBulk) OnConflictColumns(columns ...string) *CreemProductBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreemProductBindingUpsertBulk{
		create: _c,
	}
}

// CreemProductBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of CreemProductBinding nodes.
type CreemProductBindingUpsertBulk struct {
	create *CreemProductBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CreemProductBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CreemProductBindingUpsertBulk) UpdateNewValues() *CreemProductBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(creemproductbinding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreemProductBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CreemProductBindingUpsertBulk) Ignore() *CreemProductBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreemProductBindingUpsertBulk) DoNothing() *CreemProductBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreemProductBindingCreateBulk.OnConflict
// documentation for more info.
func (u *CreemProductBindingUpsertBulk) Update(set func(*CreemProductBindingUpsert)) *CreemProductBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreemProductBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (u *CreemProductBindingUpsertBulk) SetProviderInstanceID(v int64) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetProviderInstanceID(v)
	})
}

// AddProviderInstanceID adds v to the "provider_instance_id" field.
func (u *CreemProductBindingUpsertBulk) AddProviderInstanceID(v int64) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.AddProviderInstanceID(v)
	})
}

// UpdateProviderInstanceID sets the "provider_instance_id" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateProviderInstanceID() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateProviderInstanceID()
	})
}

// SetExternalProductID sets the "external_product_id" field.
func (u *CreemProductBindingUpsertBulk) SetExternalProductID(v string) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetExternalProductID(v)
	})
}

// UpdateExternalProductID sets the "external_product_id" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateExternalProductID() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateExternalProductID()
	})
}

// SetTargetType sets the "target_type" field.
func (u *CreemProductBindingUpsertBulk) SetTargetType(v string) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetTargetType(v)
	})
}

// UpdateTargetType sets the "target_type" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateTargetType() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateTargetType()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *CreemProductBindingUpsertBulk) SetPlanID(v int64) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *CreemProductBindingUpsertBulk) AddPlanID(v int64) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdatePlanID() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdatePlanID()
	})
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *CreemProductBindingUpsertBulk) ClearPlanID() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.ClearPlanID()
	})
}

// SetCreditedBalance sets the "credited_balance" field.
func (u *CreemProductBindingUpsertBulk) SetCreditedBalance(v float64) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetCreditedBalance(v)
	})
}

// AddCreditedBalance adds v to the "credited_balance" field.
func (u *CreemProductBindingUpsertBulk) AddCreditedBalance(v float64) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.AddCreditedBalance(v)
	})
}

// UpdateCreditedBalance sets the "credited_balance" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateCreditedBalance() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateCreditedBalance()
	})
}

// ClearCreditedBalance clears the value of the "credited_balance" field.
func (u *CreemProductBindingUpsertBulk) ClearCreditedBalance() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.ClearCreditedBalance()
	})
}

// SetProductName sets the "product_name" field.
func (u *CreemProductBindingUpsertBulk) SetProductName(v string) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetProductName(v)
	})
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateProductName() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateProductName()
	})
}

// SetPriceMinor sets the "price_minor" field.
func (u *CreemProductBindingUpsertBulk) SetPriceMinor(v int64) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetPriceMinor(v)
	})
}

// AddPriceMinor adds v to the "price_minor" field.
func (u *CreemProductBindingUpsertBulk) AddPriceMinor(v int64) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.AddPriceMinor(v)
	})
}

// UpdatePriceMinor sets the "price_minor" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdatePriceMinor() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdatePriceMinor()
	})
}

// SetCurrency sets the "currency" field.
func (u *CreemProductBindingUpsertBulk) SetCurrency(v string) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateCurrency() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateCurrency()
	})
}

// SetBillingType sets the "billing_type" field.
func (u *CreemProductBindingUpsertBulk) SetBillingType(v string) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetBillingType(v)
	})
}

// UpdateBillingType sets the "billing_type" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateBillingType() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateBillingType()
	})
}

// SetProductStatus sets the "product_status" field.
func (u *CreemProductBindingUpsertBulk) SetProductStatus(v string) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetProductStatus(v)
	})
}

// UpdateProductStatus sets the "product_status" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateProductStatus() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateProductStatus()
	})
}

// SetTaxMode sets the "tax_mode" field.
func (u *CreemProductBindingUpsertBulk) SetTaxMode(v string) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetTaxMode(v)
	})
}

// UpdateTaxMode sets the "tax_mode" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateTaxMode() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateTaxMode()
	})
}

// SetEnvironment sets the "environment" field.
func (u *CreemProductBindingUpsertBulk) SetEnvironment(v string) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetEnvironment(v)
	})
}

// UpdateEnvironment sets the "environment" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateEnvironment() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateEnvironment()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CreemProductBindingUpsertBulk) SetEnabled(v bool) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateEnabled() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateEnabled()
	})
}

// SetHealthStatus sets the "health_status" field.
func (u *CreemProductBindingUpsertBulk) SetHealthStatus(v string) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetHealthStatus(v)
	})
}

// UpdateHealthStatus sets the "health_status" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateHealthStatus() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateHealthStatus()
	})
}

// SetHealthReason sets the "health_reason" field.
func (u *CreemProductBindingUpsertBulk) SetHealthReason(v string) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetHealthReason(v)
	})
}

// UpdateHealthReason sets the "health_reason" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateHealthReason() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateHealthReason()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CreemProductBindingUpsertBulk) SetSortOrder(v int) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CreemProductBindingUpsertBulk) AddSortOrder(v int) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateSortOrder() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateSortOrder()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *CreemProductBindingUpsertBulk) SetLastSyncedAt(v time.Time) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateLastSyncedAt() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *CreemProductBindingUpsertBulk) ClearLastSyncedAt() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.ClearLastSyncedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CreemProductBindingUpsertBulk) SetUpdatedAt(v time.Time) *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreemProductBindingUpsertBulk) UpdateUpdatedAt() *CreemProductBindingUpsertBulk {
	return u.Update(func(s *CreemProductBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CreemProductBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CreemProductBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreemProductBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreemProductBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
