// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/creemrefundevent"
)

// CreemRefundEventCreate is the builder for creating a CreemRefundEvent entity.
type CreemRefundEventCreate struct {
	config
	mutation *CreemRefundEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEventID sets the "event_id" field.
func (_c *CreemRefundEventCreate) SetEventID(v string) *CreemRefundEventCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetProviderRefundID sets the "provider_refund_id" field.
func (_c *CreemRefundEventCreate) SetProviderRefundID(v string) *CreemRefundEventCreate {
	_c.mutation.SetProviderRefundID(v)
	return _c
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (_c *CreemRefundEventCreate) SetProviderInstanceID(v int64) *CreemRefundEventCreate {
	_c.mutation.SetProviderInstanceID(v)
	return _c
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_c *CreemRefundEventCreate) SetPaymentOrderID(v int64) *CreemRefundEventCreate {
	_c.mutation.SetPaymentOrderID(v)
	return _c
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_c *CreemRefundEventCreate) SetNillablePaymentOrderID(v *int64) *CreemRefundEventCreate {
	if v != nil {
		_c.SetPaymentOrderID(*v)
	}
	return _c
}

// SetTransactionID sets the "transaction_id" field.
func (_c *CreemRefundEventCreate) SetTransactionID(v string) *CreemRefundEventCreate {
	_c.mutation.SetTransactionID(v)
	return _c
}

// SetRefundAmountMinor sets the "refund_amount_minor" field.
func (_c *CreemRefundEventCreate) SetRefundAmountMinor(v int64) *CreemRefundEventCreate {
	_c.mutation.SetRefundAmountMinor(v)
	return _c
}

// SetCumulativeRefundedMinor sets the "cumulative_refunded_minor" field.
func (_c *CreemRefundEventCreate) SetCumulativeRefundedMinor(v int64) *CreemRefundEventCreate {
	_c.mutation.SetCumulativeRefundedMinor(v)
	return _c
}

// SetTransactionAmountPaidMinor sets the "transaction_amount_paid_minor" field.
func (_c *CreemRefundEventCreate) SetTransactionAmountPaidMinor(v int64) *CreemRefundEventCreate {
	_c.mutation.SetTransactionAmountPaidMinor(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *CreemRefundEventCreate) SetCurrency(v string) *CreemRefundEventCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetRefundRatio sets the "refund_ratio" field.
func (_c *CreemRefundEventCreate) SetRefundRatio(v float64) *CreemRefundEventCreate {
	_c.mutation.SetRefundRatio(v)
	return _c
}

// SetNillableRefundRatio sets the "refund_ratio" field if the given value is not nil.
func (_c *CreemRefundEventCreate) SetNillableRefundRatio(v *float64) *CreemRefundEventCreate {
	if v != nil {
		_c.SetRefundRatio(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CreemRefundEventCreate) SetStatus(v string) *CreemRefundEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CreemRefundEventCreate) SetNillableStatus(v *string) *CreemRefundEventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRecoverySnapshot sets the "recovery_snapshot" field.
func (_c *CreemRefundEventCreate) SetRecoverySnapshot(v map[string]interface{}) *CreemRefundEventCreate {
	_c.mutation.SetRecoverySnapshot(v)
	return _c
}

// SetRawPayload sets the "raw_payload" field.
func (_c *CreemRefundEventCreate) SetRawPayload(v map[string]interface{}) *CreemRefundEventCreate {
	_c.mutation.SetRawPayload(v)
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *CreemRefundEventCreate) SetAttempts(v int) *CreemRefundEventCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *CreemRefundEventCreate) SetNillableAttempts(v *int) *CreemRefundEventCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *CreemRefundEventCreate) SetLastError(v string) *CreemRefundEventCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *CreemRefundEventCreate) SetNillableLastError(v *string) *CreemRefundEventCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetProcessedAt sets the "processed_at" field.
func (_c *CreemRefundEventCreate) SetProcessedAt(v time.Time) *CreemRefundEventCreate {
	_c.mutation.SetProcessedAt(v)
	return _c
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_c *CreemRefundEventCreate) SetNillableProcessedAt(v *time.Time) *CreemRefundEventCreate {
	if v != nil {
		_c.SetProcessedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CreemRefundEventCreate) SetCreatedAt(v time.Time) *CreemRefundEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CreemRefundEventCreate) SetNillableCreatedAt(v *time.Time) *CreemRefundEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CreemRefundEventCreate) SetUpdatedAt(v time.Time) *CreemRefundEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CreemRefundEventCreate) SetNillableUpdatedAt(v *time.Time) *CreemRefundEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CreemRefundEventMutation object of the builder.
func (_c *CreemRefundEventCreate) Mutation() *CreemRefundEventMutation {
	return _c.mutation
}

// Save creates the CreemRefundEvent in the database.
func (_c *CreemRefundEventCreate) Save(ctx context.Context) (*CreemRefundEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CreemRefundEventCreate) SaveX(ctx context.Context) *CreemRefundEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreemRefundEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreemRefundEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CreemRefundEventCreate) defaults() {
	if _, ok := _c.mutation.RefundRatio(); !ok {
		v := creemrefundevent.DefaultRefundRatio
		_c.mutation.SetRefundRatio(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := creemrefundevent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := creemrefundevent.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := creemrefundevent.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := creemrefundevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := creemrefundevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CreemRefundEventCreate) check() error {
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "CreemRefundEvent.event_id"`)}
	}
	if v, ok := _c.mutation.EventID(); ok {
		if err := creemrefundevent.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "CreemRefundEvent.event_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderRefundID(); !ok {
		return &ValidationError{Name: "provider_refund_id", err: errors.New(`ent: missing required field "CreemRefundEvent.provider_refund_id"`)}
	}
	if v, ok := _c.mutation.ProviderRefundID(); ok {
		if err := creemrefundevent.ProviderRefundIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_refund_id", err: fmt.Errorf(`ent: validator failed for field "CreemRefundEvent.provider_refund_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderInstanceID(); !ok {
		return &ValidationError{Name: "provider_instance_id", err: errors.New(`ent: missing required field "CreemRefundEvent.provider_instance_id"`)}
	}
	if _, ok := _c.mutation.TransactionID(); !ok {
		return &ValidationError{Name: "transaction_id", err: errors.New(`ent: missing required field "CreemRefundEvent.transaction_id"`)}
	}
	if v, ok := _c.mutation.TransactionID(); ok {
		if err := creemrefundevent.TransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "transaction_id", err: fmt.Errorf(`ent: validator failed for field "CreemRefundEvent.transaction_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RefundAmountMinor(); !ok {
		return &ValidationError{Name: "refund_amount_minor", err: errors.New(`ent: missing required field "CreemRefundEvent.refund_amount_minor"`)}
	}
	if _, ok := _c.mutation.CumulativeRefundedMinor(); !ok {
		return &ValidationError{Name: "cumulative_refunded_minor", err: errors.New(`ent: missing required field "CreemRefundEvent.cumulative_refunded_minor"`)}
	}
	if _, ok := _c.mutation.TransactionAmountPaidMinor(); !ok {
		return &ValidationError{Name: "transaction_amount_paid_minor", err: errors.New(`ent: missing required field "CreemRefundEvent.transaction_amount_paid_minor"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "CreemRefundEvent.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := creemrefundevent.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CreemRefundEvent.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RefundRatio(); !ok {
		return &ValidationError{Name: "refund_ratio", err: errors.New(`ent: missing required field "CreemRefundEvent.refund_ratio"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CreemRefundEvent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := creemrefundevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CreemRefundEvent.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "CreemRefundEvent.attempts"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "CreemRefundEvent.last_error"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CreemRefundEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CreemRefundEvent.updated_at"`)}
	}
	return nil
}

func (_c *CreemRefundEventCreate) sqlSave(ctx context.Context) (*CreemRefundEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CreemRefundEventCreate) createSpec() (*CreemRefundEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &CreemRefundEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(creemrefundevent.Table, sqlgraph.NewFieldSpec(creemrefundevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.EventID(); ok {
		_spec.SetField(creemrefundevent.FieldEventID, field.TypeString, value)
		_node.EventID = value
	}
	if value, ok := _c.mutation.ProviderRefundID(); ok {
		_spec.SetField(creemrefundevent.FieldProviderRefundID, field.TypeString, value)
		_node.ProviderRefundID = value
	}
	if value, ok := _c.mutation.ProviderInstanceID(); ok {
		_spec.SetField(creemrefundevent.FieldProviderInstanceID, field.TypeInt64, value)
		_node.ProviderInstanceID = value
	}
	if value, ok := _c.mutation.PaymentOrderID(); ok {
		_spec.SetField(creemrefundevent.FieldPaymentOrderID, field.TypeInt64, value)
		_node.PaymentOrderID = &value
	}
	if value, ok := _c.mutation.TransactionID(); ok {
		_spec.SetField(creemrefundevent.FieldTransactionID, field.TypeString, value)
		_node.TransactionID = value
	}
	if value, ok := _c.mutation.RefundAmountMinor(); ok {
		_spec.SetField(creemrefundevent.FieldRefundAmountMinor, field.TypeInt64, value)
		_node.RefundAmountMinor = value
	}
	if value, ok := _c.mutation.CumulativeRefundedMinor(); ok {
		_spec.SetField(creemrefundevent.FieldCumulativeRefundedMinor, field.TypeInt64, value)
		_node.CumulativeRefundedMinor = value
	}
	if value, ok := _c.mutation.TransactionAmountPaidMinor(); ok {
		_spec.SetField(creemrefundevent.FieldTransactionAmountPaidMinor, field.TypeInt64, value)
		_node.TransactionAmountPaidMinor = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(creemrefundevent.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.RefundRatio(); ok {
		_spec.SetField(creemrefundevent.FieldRefundRatio, field.TypeFloat64, value)
		_node.RefundRatio = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(creemrefundevent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RecoverySnapshot(); ok {
		_spec.SetField(creemrefundevent.FieldRecoverySnapshot, field.TypeJSON, value)
		_node.RecoverySnapshot = value
	}
	if value, ok := _c.mutation.RawPayload(); ok {
		_spec.SetField(creemrefundevent.FieldRawPayload, field.TypeJSON, value)
		_node.RawPayload = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(creemrefundevent.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(creemrefundevent.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.ProcessedAt(); ok {
		_spec.SetField(creemrefundevent.FieldProcessedAt, field.TypeTime, value)
		_node.ProcessedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(creemrefundevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(creemrefundevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreemRefundEvent.Create().
//		SetEventID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreemRefundEventUpsert) {
//			SetEventID(v+v).
//		}).
//		Exec(ctx)
func (_c *CreemRefundEventCreate) OnConflict(opts ...sql.ConflictOption) *CreemRefundEventUpsertOne {
	_c.conflict = opts
	return &CreemRefundEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreemRefundEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreemRefundEventCreate) OnConflictColumns(columns ...string) *CreemRefundEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreemRefundEventUpsertOne{
		create: _c,
	}
}

type (
	// CreemRefundEventUpsertOne is the builder for "upsert"-ing
	//  one CreemRefundEvent node.
	CreemRefundEventUpsertOne struct {
		create *CreemRefundEventCreate
	}

	// CreemRefundEventUpsert is the "OnConflict" setter.
	CreemRefundEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetEventID sets the "event_id" field.
func (u *CreemRefundEventUpsert) SetEventID(v string) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldEventID, v)
	return u
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateEventID() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldEventID)
	return u
}

// SetProviderRefundID sets the "provider_refund_id" field.
func (u *CreemRefundEventUpsert) SetProviderRefundID(v string) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldProviderRefundID, v)
	return u
}

// UpdateProviderRefundID sets the "provider_refund_id" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateProviderRefundID() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldProviderRefundID)
	return u
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (u *CreemRefundEventUpsert) SetProviderInstanceID(v int64) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldProviderInstanceID, v)
	return u
}

// UpdateProviderInstanceID sets the "provider_instance_id" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateProviderInstanceID() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldProviderInstanceID)
	return u
}

// AddProviderInstanceID adds v to the "provider_instance_id" field.
func (u *CreemRefundEventUpsert) AddProviderInstanceID(v int64) *CreemRefundEventUpsert {
	u.Add(creemrefundevent.FieldProviderInstanceID, v)
	return u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *CreemRefundEventUpsert) SetPaymentOrderID(v int64) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldPaymentOrderID, v)
	return u
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdatePaymentOrderID() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldPaymentOrderID)
	return u
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *CreemRefundEventUpsert) AddPaymentOrderID(v int64) *CreemRefundEventUpsert {
	u.Add(creemrefundevent.FieldPaymentOrderID, v)
	return u
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *CreemRefundEventUpsert) ClearPaymentOrderID() *CreemRefundEventUpsert {
	u.SetNull(creemrefundevent.FieldPaymentOrderID)
	return u
}

// SetTransactionID sets the "transaction_id" field.
func (u *CreemRefundEventUpsert) SetTransactionID(v string) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldTransactionID, v)
	return u
}

// UpdateTransactionID sets the "transaction_id" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateTransactionID() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldTransactionID)
	return u
}

// SetRefundAmountMinor sets the "refund_amount_minor" field.
func (u *CreemRefundEventUpsert) SetRefundAmountMinor(v int64) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldRefundAmountMinor, v)
	return u
}

// UpdateRefundAmountMinor sets the "refund_amount_minor" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateRefundAmountMinor() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldRefundAmountMinor)
	return u
}

// AddRefundAmountMinor adds v to the "refund_amount_minor" field.
func (u *CreemRefundEventUpsert) AddRefundAmountMinor(v int64) *CreemRefundEventUpsert {
	u.Add(creemrefundevent.FieldRefundAmountMinor, v)
	return u
}

// SetCumulativeRefundedMinor sets the "cumulative_refunded_minor" field.
func (u *CreemRefundEventUpsert) SetCumulativeRefundedMinor(v int64) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldCumulativeRefundedMinor, v)
	return u
}

// UpdateCumulativeRefundedMinor sets the "cumulative_refunded_minor" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateCumulativeRefundedMinor() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldCumulativeRefundedMinor)
	return u
}

// AddCumulativeRefundedMinor adds v to the "cumulative_refunded_minor" field.
func (u *CreemRefundEventUpsert) AddCumulativeRefundedMinor(v int64) *CreemRefundEventUpsert {
	u.Add(creemrefundevent.FieldCumulativeRefundedMinor, v)
	return u
}

// SetTransactionAmountPaidMinor sets the "transaction_amount_paid_minor" field.
func (u *CreemRefundEventUpsert) SetTransactionAmountPaidMinor(v int64) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldTransactionAmountPaidMinor, v)
	return u
}

// UpdateTransactionAmountPaidMinor sets the "transaction_amount_paid_minor" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateTransactionAmountPaidMinor() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldTransactionAmountPaidMinor)
	return u
}

// AddTransactionAmountPaidMinor adds v to the "transaction_amount_paid_minor" field.
func (u *CreemRefundEventUpsert) AddTransactionAmountPaidMinor(v int64) *CreemRefundEventUpsert {
	u.Add(creemrefundevent.FieldTransactionAmountPaidMinor, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *CreemRefundEventUpsert) SetCurrency(v string) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateCurrency() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldCurrency)
	return u
}

// SetRefundRatio sets the "refund_ratio" field.
func (u *CreemRefundEventUpsert) SetRefundRatio(v float64) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldRefundRatio, v)
	return u
}

// UpdateRefundRatio sets the "refund_ratio" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateRefundRatio() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldRefundRatio)
	return u
}

// AddRefundRatio adds v to the "refund_ratio" field.
func (u *CreemRefundEventUpsert) AddRefundRatio(v float64) *CreemRefundEventUpsert {
	u.Add(creemrefundevent.FieldRefundRatio, v)
	return u
}

// SetStatus sets the "status" field.
func (u *CreemRefundEventUpsert) SetStatus(v string) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateStatus() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldStatus)
	return u
}

// SetRecoverySnapshot sets the "recovery_snapshot" field.
func (u *CreemRefundEventUpsert) SetRecoverySnapshot(v map[string]interface{}) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldRecoverySnapshot, v)
	return u
}

// UpdateRecoverySnapshot sets the "recovery_snapshot" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateRecoverySnapshot() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldRecoverySnapshot)
	return u
}

// ClearRecoverySnapshot clears the value of the "recovery_snapshot" field.
func (u *CreemRefundEventUpsert) ClearRecoverySnapshot() *CreemRefundEventUpsert {
	u.SetNull(creemrefundevent.FieldRecoverySnapshot)
	return u
}

// SetRawPayload sets the "raw_payload" field.
func (u *CreemRefundEventUpsert) SetRawPayload(v map[string]interface{}) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldRawPayload, v)
	return u
}

// UpdateRawPayload sets the "raw_payload" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateRawPayload() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldRawPayload)
	return u
}

// ClearRawPayload clears the value of the "raw_payload" field.
func (u *CreemRefundEventUpsert) ClearRawPayload() *CreemRefundEventUpsert {
	u.SetNull(creemrefundevent.FieldRawPayload)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *CreemRefundEventUpsert) SetAttempts(v int) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateAttempts() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *CreemRefundEventUpsert) AddAttempts(v int) *CreemRefundEventUpsert {
	u.Add(creemrefundevent.FieldAttempts, v)
	return u
}

// SetLastError sets the "last_error" field.
func (u *CreemRefundEventUpsert) SetLastError(v string) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateLastError() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldLastError)
	return u
}

// SetProcessedAt sets the "processed_at" field.
func (u *CreemRefundEventUpsert) SetProcessedAt(v time.Time) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldProcessedAt, v)
	return u
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateProcessedAt() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldProcessedAt)
	return u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *CreemRefundEventUpsert) ClearProcessedAt() *CreemRefundEventUpsert {
	u.SetNull(creemrefundevent.FieldProcessedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CreemRefundEventUpsert) SetUpdatedAt(v time.Time) *CreemRefundEventUpsert {
	u.Set(creemrefundevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreemRefundEventUpsert) UpdateUpdatedAt() *CreemRefundEventUpsert {
	u.SetExcluded(creemrefundevent.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CreemRefundEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CreemRefundEventUpsertOne) UpdateNewValues() *CreemRefundEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(creemrefundevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreemRefundEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CreemRefundEventUpsertOne) Ignore() *CreemRefundEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreemRefundEventUpsertOne) DoNothing() *CreemRefundEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreemRefundEventCreate.OnConflict
// documentation for more info.
func (u *CreemRefundEventUpsertOne) Update(set func(*CreemRefundEventUpsert)) *CreemRefundEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreemRefundEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetEventID sets the "event_id" field.
func (u *CreemRefundEventUpsertOne) SetEventID(v string) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetEventID(v)
	})
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateEventID() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateEventID()
	})
}

// SetProviderRefundID sets the "provider_refund_id" field.
func (u *CreemRefundEventUpsertOne) SetProviderRefundID(v string) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetProviderRefundID(v)
	})
}

// UpdateProviderRefundID sets the "provider_refund_id" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateProviderRefundID() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateProviderRefundID()
	})
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (u *CreemRefundEventUpsertOne) SetProviderInstanceID(v int64) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetProviderInstanceID(v)
	})
}

// AddProviderInstanceID adds v to the "provider_instance_id" field.
func (u *CreemRefundEventUpsertOne) AddProviderInstanceID(v int64) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.AddProviderInstanceID(v)
	})
}

// UpdateProviderInstanceID sets the "provider_instance_id" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateProviderInstanceID() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateProviderInstanceID()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *CreemRefundEventUpsertOne) SetPaymentOrderID(v int64) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *CreemRefundEventUpsertOne) AddPaymentOrderID(v int64) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdatePaymentOrderID() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *CreemRefundEventUpsertOne) ClearPaymentOrderID() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.ClearPaymentOrderID()
	})
}

// SetTransactionID sets the "transaction_id" field.
func (u *CreemRefundEventUpsertOne) SetTransactionID(v string) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetTransactionID(v)
	})
}

// UpdateTransactionID sets the "transaction_id" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateTransactionID() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateTransactionID()
	})
}

// SetRefundAmountMinor sets the "refund_amount_minor" field.
func (u *CreemRefundEventUpsertOne) SetRefundAmountMinor(v int64) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetRefundAmountMinor(v)
	})
}

// AddRefundAmountMinor adds v to the "refund_amount_minor" field.
func (u *CreemRefundEventUpsertOne) AddRefundAmountMinor(v int64) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.AddRefundAmountMinor(v)
	})
}

// UpdateRefundAmountMinor sets the "refund_amount_minor" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateRefundAmountMinor() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateRefundAmountMinor()
	})
}

// SetCumulativeRefundedMinor sets the "cumulative_refunded_minor" field.
func (u *CreemRefundEventUpsertOne) SetCumulativeRefundedMinor(v int64) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetCumulativeRefundedMinor(v)
	})
}

// AddCumulativeRefundedMinor adds v to the "cumulative_refunded_minor" field.
func (u *CreemRefundEventUpsertOne) AddCumulativeRefundedMinor(v int64) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.AddCumulativeRefundedMinor(v)
	})
}

// UpdateCumulativeRefundedMinor sets the "cumulative_refunded_minor" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateCumulativeRefundedMinor() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateCumulativeRefundedMinor()
	})
}

// SetTransactionAmountPaidMinor sets the "transaction_amount_paid_minor" field.
func (u *CreemRefundEventUpsertOne) SetTransactionAmountPaidMinor(v int64) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetTransactionAmountPaidMinor(v)
	})
}

// AddTransactionAmountPaidMinor adds v to the "transaction_amount_paid_minor" field.
func (u *CreemRefundEventUpsertOne) AddTransactionAmountPaidMinor(v int64) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.AddTransactionAmountPaidMinor(v)
	})
}

// UpdateTransactionAmountPaidMinor sets the "transaction_amount_paid_minor" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateTransactionAmountPaidMinor() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateTransactionAmountPaidMinor()
	})
}

// SetCurrency sets the "currency" field.
func (u *CreemRefundEventUpsertOne) SetCurrency(v string) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateCurrency() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateCurrency()
	})
}

// SetRefundRatio sets the "refund_ratio" field.
func (u *CreemRefundEventUpsertOne) SetRefundRatio(v float64) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetRefundRatio(v)
	})
}

// AddRefundRatio adds v to the "refund_ratio" field.
func (u *CreemRefundEventUpsertOne) AddRefundRatio(v float64) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.AddRefundRatio(v)
	})
}

// UpdateRefundRatio sets the "refund_ratio" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateRefundRatio() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateRefundRatio()
	})
}

// SetStatus sets the "status" field.
func (u *CreemRefundEventUpsertOne) SetStatus(v string) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateStatus() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateStatus()
	})
}

// SetRecoverySnapshot sets the "recovery_snapshot" field.
func (u *CreemRefundEventUpsertOne) SetRecoverySnapshot(v map[string]interface{}) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetRecoverySnapshot(v)
	})
}

// UpdateRecoverySnapshot sets the "recovery_snapshot" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateRecoverySnapshot() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateRecoverySnapshot()
	})
}

// ClearRecoverySnapshot clears the value of the "recovery_snapshot" field.
func (u *CreemRefundEventUpsertOne) ClearRecoverySnapshot() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.ClearRecoverySnapshot()
	})
}

// SetRawPayload sets the "raw_payload" field.
func (u *CreemRefundEventUpsertOne) SetRawPayload(v map[string]interface{}) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetRawPayload(v)
	})
}

// UpdateRawPayload sets the "raw_payload" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateRawPayload() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateRawPayload()
	})
}

// ClearRawPayload clears the value of the "raw_payload" field.
func (u *CreemRefundEventUpsertOne) ClearRawPayload() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.ClearRawPayload()
	})
}

// SetAttempts sets the "attempts" field.
func (u *CreemRefundEventUpsertOne) SetAttempts(v int) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *CreemRefundEventUpsertOne) AddAttempts(v int) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateAttempts() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *CreemRefundEventUpsertOne) SetLastError(v string) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateLastError() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateLastError()
	})
}

// SetProcessedAt sets the "processed_at" field.
func (u *CreemRefundEventUpsertOne) SetProcessedAt(v time.Time) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetProcessedAt(v)
	})
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateProcessedAt() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateProcessedAt()
	})
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *CreemRefundEventUpsertOne) ClearProcessedAt() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.ClearProcessedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CreemRefundEventUpsertOne) SetUpdatedAt(v time.Time) *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreemRefundEventUpsertOne) UpdateUpdatedAt() *CreemRefundEventUpsertOne {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CreemRefundEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreemRefundEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreemRefundEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CreemRefundEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CreemRefundEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CreemRefundEventCreateBulk is the builder for creating many CreemRefundEvent entities in bulk.
type CreemRefundEventCreateBulk struct {
	config
	err      error
	builders []*CreemRefundEventCreate
	conflict []sql.ConflictOption
}

// Save creates the CreemRefundEvent entities in the database.
func (_c *CreemRefundEventCreateBulk) Save(ctx context.Context) ([]*CreemRefundEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CreemRefundEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CreemRefundEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CreemRefundEventCreateBulk) SaveX(ctx context.Context) []*CreemRefundEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreemRefundEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreemRefundEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreemRefundEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreemRefundEventUpsert) {
//			SetEventID(v+v).
//		}).
//		Exec(ctx)
func (_c *CreemRefundEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *CreemRefundEventUpsertBulk {
	_c.conflict = opts
	return &CreemRefundEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreemRefundEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreemRefundEventCreateBulk) OnConflictColumns(columns ...string) *CreemRefundEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreemRefundEventUpsertBulk{
		create: _c,
	}
}

// CreemRefundEventUpsertBulk is the builder for "upsert"-ing
// a bulk of CreemRefundEvent nodes.
type CreemRefundEventUpsertBulk struct {
	create *CreemRefundEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CreemRefundEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CreemRefundEventUpsertBulk) UpdateNewValues() *CreemRefundEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(creemrefundevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreemRefundEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CreemRefundEventUpsertBulk) Ignore() *CreemRefundEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreemRefundEventUpsertBulk) DoNothing() *CreemRefundEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreemRefundEventCreateBulk.OnConflict
// documentation for more info.
func (u *CreemRefundEventUpsertBulk) Update(set func(*CreemRefundEventUpsert)) *CreemRefundEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreemRefundEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetEventID sets the "event_id" field.
func (u *CreemRefundEventUpsertBulk) SetEventID(v string) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetEventID(v)
	})
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateEventID() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateEventID()
	})
}

// SetProviderRefundID sets the "provider_refund_id" field.
func (u *CreemRefundEventUpsertBulk) SetProviderRefundID(v string) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetProviderRefundID(v)
	})
}

// UpdateProviderRefundID sets the "provider_refund_id" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateProviderRefundID() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateProviderRefundID()
	})
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (u *CreemRefundEventUpsertBulk) SetProviderInstanceID(v int64) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetProviderInstanceID(v)
	})
}

// AddProviderInstanceID adds v to the "provider_instance_id" field.
func (u *CreemRefundEventUpsertBulk) AddProviderInstanceID(v int64) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.AddProviderInstanceID(v)
	})
}

// UpdateProviderInstanceID sets the "provider_instance_id" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateProviderInstanceID() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateProviderInstanceID()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *CreemRefundEventUpsertBulk) SetPaymentOrderID(v int64) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *CreemRefundEventUpsertBulk) AddPaymentOrderID(v int64) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdatePaymentOrderID() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *CreemRefundEventUpsertBulk) ClearPaymentOrderID() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.ClearPaymentOrderID()
	})
}

// SetTransactionID sets the "transaction_id" field.
func (u *CreemRefundEventUpsertBulk) SetTransactionID(v string) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetTransactionID(v)
	})
}

// UpdateTransactionID sets the "transaction_id" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateTransactionID() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateTransactionID()
	})
}

// SetRefundAmountMinor sets the "refund_amount_minor" field.
func (u *CreemRefundEventUpsertBulk) SetRefundAmountMinor(v int64) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetRefundAmountMinor(v)
	})
}

// AddRefundAmountMinor adds v to the "refund_amount_minor" field.
func (u *CreemRefundEventUpsertBulk) AddRefundAmountMinor(v int64) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.AddRefundAmountMinor(v)
	})
}

// UpdateRefundAmountMinor sets the "refund_amount_minor" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateRefundAmountMinor() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateRefundAmountMinor()
	})
}

// SetCumulativeRefundedMinor sets the "cumulative_refunded_minor" field.
func (u *CreemRefundEventUpsertBulk) SetCumulativeRefundedMinor(v int64) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetCumulativeRefundedMinor(v)
	})
}

// AddCumulativeRefundedMinor adds v to the "cumulative_refunded_minor" field.
func (u *CreemRefundEventUpsertBulk) AddCumulativeRefundedMinor(v int64) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.AddCumulativeRefundedMinor(v)
	})
}

// UpdateCumulativeRefundedMinor sets the "cumulative_refunded_minor" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateCumulativeRefundedMinor() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateCumulativeRefundedMinor()
	})
}

// SetTransactionAmountPaidMinor sets the "transaction_amount_paid_minor" field.
func (u *CreemRefundEventUpsertBulk) SetTransactionAmountPaidMinor(v int64) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetTransactionAmountPaidMinor(v)
	})
}

// AddTransactionAmountPaidMinor adds v to the "transaction_amount_paid_minor" field.
func (u *CreemRefundEventUpsertBulk) AddTransactionAmountPaidMinor(v int64) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.AddTransactionAmountPaidMinor(v)
	})
}

// UpdateTransactionAmountPaidMinor sets the "transaction_amount_paid_minor" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateTransactionAmountPaidMinor() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateTransactionAmountPaidMinor()
	})
}

// SetCurrency sets the "currency" field.
func (u *CreemRefundEventUpsertBulk) SetCurrency(v string) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateCurrency() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateCurrency()
	})
}

// SetRefundRatio sets the "refund_ratio" field.
func (u *CreemRefundEventUpsertBulk) SetRefundRatio(v float64) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetRefundRatio(v)
	})
}

// AddRefundRatio adds v to the "refund_ratio" field.
func (u *CreemRefundEventUpsertBulk) AddRefundRatio(v float64) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.AddRefundRatio(v)
	})
}

// UpdateRefundRatio sets the "refund_ratio" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateRefundRatio() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateRefundRatio()
	})
}

// SetStatus sets the "status" field.
func (u *CreemRefundEventUpsertBulk) SetStatus(v string) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateStatus() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateStatus()
	})
}

// SetRecoverySnapshot sets the "recovery_snapshot" field.
func (u *CreemRefundEventUpsertBulk) SetRecoverySnapshot(v map[string]interface{}) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetRecoverySnapshot(v)
	})
}

// UpdateRecoverySnapshot sets the "recovery_snapshot" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateRecoverySnapshot() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateRecoverySnapshot()
	})
}

// ClearRecoverySnapshot clears the value of the "recovery_snapshot" field.
func (u *CreemRefundEventUpsertBulk) ClearRecoverySnapshot() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.ClearRecoverySnapshot()
	})
}

// SetRawPayload sets the "raw_payload" field.
func (u *CreemRefundEventUpsertBulk) SetRawPayload(v map[string]interface{}) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetRawPayload(v)
	})
}

// UpdateRawPayload sets the "raw_payload" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateRawPayload() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateRawPayload()
	})
}

// ClearRawPayload clears the value of the "raw_payload" field.
func (u *CreemRefundEventUpsertBulk) ClearRawPayload() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.ClearRawPayload()
	})
}

// SetAttempts sets the "attempts" field.
func (u *CreemRefundEventUpsertBulk) SetAttempts(v int) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *CreemRefundEventUpsertBulk) AddAttempts(v int) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateAttempts() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *CreemRefundEventUpsertBulk) SetLastError(v string) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateLastError() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateLastError()
	})
}

// SetProcessedAt sets the "processed_at" field.
func (u *CreemRefundEventUpsertBulk) SetProcessedAt(v time.Time) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetProcessedAt(v)
	})
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateProcessedAt() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateProcessedAt()
	})
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *CreemRefundEventUpsertBulk) ClearProcessedAt() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.ClearProcessedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CreemRefundEventUpsertBulk) SetUpdatedAt(v time.Time) *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreemRefundEventUpsertBulk) UpdateUpdatedAt() *CreemRefundEventUpsertBulk {
	return u.Update(func(s *CreemRefundEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CreemRefundEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CreemRefundEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreemRefundEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreemRefundEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
