// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userglobalplansubscription"
)

// UserGlobalPlanSubscriptionUpdate is the builder for updating UserGlobalPlanSubscription entities.
type UserGlobalPlanSubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *UserGlobalPlanSubscriptionMutation
}

// Where appends a list predicates to the UserGlobalPlanSubscriptionUpdate builder.
func (_u *UserGlobalPlanSubscriptionUpdate) Where(ps ...predicate.UserGlobalPlanSubscription) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetDeletedAt(v time.Time) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableDeletedAt(v *time.Time) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserGlobalPlanSubscriptionUpdate) ClearDeletedAt() *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetUserID(v int64) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableUserID(v *int64) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetPlanID(v int64) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillablePlanID(v *int64) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetPlanCategory sets the "plan_category" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetPlanCategory(v string) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetPlanCategory(v)
	return _u
}

// SetNillablePlanCategory sets the "plan_category" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillablePlanCategory(v *string) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetPlanCategory(*v)
	}
	return _u
}

// SetApplicableGroupMode sets the "applicable_group_mode" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetApplicableGroupMode(v string) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetApplicableGroupMode(v)
	return _u
}

// SetNillableApplicableGroupMode sets the "applicable_group_mode" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableApplicableGroupMode(v *string) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetApplicableGroupMode(*v)
	}
	return _u
}

// SetApplicableGroupIds sets the "applicable_group_ids" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetApplicableGroupIds(v []int64) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetApplicableGroupIds(v)
	return _u
}

// AppendApplicableGroupIds appends value to the "applicable_group_ids" field.
func (_u *UserGlobalPlanSubscriptionUpdate) AppendApplicableGroupIds(v []int64) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.AppendApplicableGroupIds(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetStatus(v string) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableStatus(v *string) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetStartsAt(v time.Time) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableStartsAt(v *time.Time) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetExpiresAt(v time.Time) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableExpiresAt(v *time.Time) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetCurrentPeriodStart(v time.Time) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetCurrentPeriodStart(v)
	return _u
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableCurrentPeriodStart(v *time.Time) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetCurrentPeriodStart(*v)
	}
	return _u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetCurrentPeriodEnd(v time.Time) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetCurrentPeriodEnd(v)
	return _u
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableCurrentPeriodEnd(v *time.Time) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetCurrentPeriodEnd(*v)
	}
	return _u
}

// SetQuotaPeriod sets the "quota_period" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetQuotaPeriod(v string) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetQuotaPeriod(v)
	return _u
}

// SetNillableQuotaPeriod sets the "quota_period" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableQuotaPeriod(v *string) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetQuotaPeriod(*v)
	}
	return _u
}

// SetQuotaLimitUsd sets the "quota_limit_usd" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetQuotaLimitUsd(v float64) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.ResetQuotaLimitUsd()
	_u.mutation.SetQuotaLimitUsd(v)
	return _u
}

// SetNillableQuotaLimitUsd sets the "quota_limit_usd" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableQuotaLimitUsd(v *float64) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetQuotaLimitUsd(*v)
	}
	return _u
}

// AddQuotaLimitUsd adds value to the "quota_limit_usd" field.
func (_u *UserGlobalPlanSubscriptionUpdate) AddQuotaLimitUsd(v float64) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.AddQuotaLimitUsd(v)
	return _u
}

// SetQuotaUsedUsd sets the "quota_used_usd" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetQuotaUsedUsd(v float64) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.ResetQuotaUsedUsd()
	_u.mutation.SetQuotaUsedUsd(v)
	return _u
}

// SetNillableQuotaUsedUsd sets the "quota_used_usd" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableQuotaUsedUsd(v *float64) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetQuotaUsedUsd(*v)
	}
	return _u
}

// AddQuotaUsedUsd adds value to the "quota_used_usd" field.
func (_u *UserGlobalPlanSubscriptionUpdate) AddQuotaUsedUsd(v float64) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.AddQuotaUsedUsd(v)
	return _u
}

// SetTierRank sets the "tier_rank" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetTierRank(v int) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.ResetTierRank()
	_u.mutation.SetTierRank(v)
	return _u
}

// SetNillableTierRank sets the "tier_rank" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableTierRank(v *int) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetTierRank(*v)
	}
	return _u
}

// AddTierRank adds value to the "tier_rank" field.
func (_u *UserGlobalPlanSubscriptionUpdate) AddTierRank(v int) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.AddTierRank(v)
	return _u
}

// SetPlanNameSnapshot sets the "plan_name_snapshot" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetPlanNameSnapshot(v string) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetPlanNameSnapshot(v)
	return _u
}

// SetNillablePlanNameSnapshot sets the "plan_name_snapshot" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillablePlanNameSnapshot(v *string) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetPlanNameSnapshot(*v)
	}
	return _u
}

// SetSourceOrderID sets the "source_order_id" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetSourceOrderID(v int64) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetSourceOrderID(v)
	return _u
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableSourceOrderID(v *int64) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetSourceOrderID(*v)
	}
	return _u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (_u *UserGlobalPlanSubscriptionUpdate) ClearSourceOrderID() *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.ClearSourceOrderID()
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetAssignedBy(v int64) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableAssignedBy(v *int64) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (_u *UserGlobalPlanSubscriptionUpdate) ClearAssignedBy() *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.ClearAssignedBy()
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetAssignedAt(v time.Time) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableAssignedAt(v *time.Time) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNotes(v string) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableNotes(v *string) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UserGlobalPlanSubscriptionUpdate) ClearNotes() *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetLastResetAt sets the "last_reset_at" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetLastResetAt(v time.Time) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetLastResetAt(v)
	return _u
}

// SetNillableLastResetAt sets the "last_reset_at" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableLastResetAt(v *time.Time) *UserGlobalPlanSubscriptionUpdate {
	if v != nil {
		_u.SetLastResetAt(*v)
	}
	return _u
}

// ClearLastResetAt clears the value of the "last_reset_at" field.
func (_u *UserGlobalPlanSubscriptionUpdate) ClearLastResetAt() *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.ClearLastResetAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetMetadata(v map[string]interface{}) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *UserGlobalPlanSubscriptionUpdate) ClearMetadata() *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserGlobalPlanSubscriptionUpdate) SetUpdatedAt(v time.Time) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserGlobalPlanSubscriptionUpdate) SetUser(v *User) *UserGlobalPlanSubscriptionUpdate {
	return _u.SetUserID(v.ID)
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_u *UserGlobalPlanSubscriptionUpdate) SetPlan(v *SubscriptionPlan) *UserGlobalPlanSubscriptionUpdate {
	return _u.SetPlanID(v.ID)
}

// SetSourceOrder sets the "source_order" edge to the PaymentOrder entity.
func (_u *UserGlobalPlanSubscriptionUpdate) SetSourceOrder(v *PaymentOrder) *UserGlobalPlanSubscriptionUpdate {
	return _u.SetSourceOrderID(v.ID)
}

// SetAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID.
func (_u *UserGlobalPlanSubscriptionUpdate) SetAssignedByUserID(id int64) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.SetAssignedByUserID(id)
	return _u
}

// SetNillableAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdate) SetNillableAssignedByUserID(id *int64) *UserGlobalPlanSubscriptionUpdate {
	if id != nil {
		_u = _u.SetAssignedByUserID(*id)
	}
	return _u
}

// SetAssignedByUser sets the "assigned_by_user" edge to the User entity.
func (_u *UserGlobalPlanSubscriptionUpdate) SetAssignedByUser(v *User) *UserGlobalPlanSubscriptionUpdate {
	return _u.SetAssignedByUserID(v.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *UserGlobalPlanSubscriptionUpdate) AddUsageLogIDs(ids ...int64) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *UserGlobalPlanSubscriptionUpdate) AddUsageLogs(v ...*UsageLog) *UserGlobalPlanSubscriptionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the UserGlobalPlanSubscriptionMutation object of the builder.
func (_u *UserGlobalPlanSubscriptionUpdate) Mutation() *UserGlobalPlanSubscriptionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserGlobalPlanSubscriptionUpdate) ClearUser() *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearPlan clears the "plan" edge to the SubscriptionPlan entity.
func (_u *UserGlobalPlanSubscriptionUpdate) ClearPlan() *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// ClearSourceOrder clears the "source_order" edge to the PaymentOrder entity.
func (_u *UserGlobalPlanSubscriptionUpdate) ClearSourceOrder() *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.ClearSourceOrder()
	return _u
}

// ClearAssignedByUser clears the "assigned_by_user" edge to the User entity.
func (_u *UserGlobalPlanSubscriptionUpdate) ClearAssignedByUser() *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.ClearAssignedByUser()
	return _u
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *UserGlobalPlanSubscriptionUpdate) ClearUsageLogs() *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *UserGlobalPlanSubscriptionUpdate) RemoveUsageLogIDs(ids ...int64) *UserGlobalPlanSubscriptionUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *UserGlobalPlanSubscriptionUpdate) RemoveUsageLogs(v ...*UsageLog) *UserGlobalPlanSubscriptionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserGlobalPlanSubscriptionUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserGlobalPlanSubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserGlobalPlanSubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserGlobalPlanSubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserGlobalPlanSubscriptionUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if userglobalplansubscription.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized userglobalplansubscription.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := userglobalplansubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserGlobalPlanSubscriptionUpdate) check() error {
	if v, ok := _u.mutation.PlanCategory(); ok {
		if err := userglobalplansubscription.PlanCategoryValidator(v); err != nil {
			return &ValidationError{Name: "plan_category", err: fmt.Errorf(`ent: validator failed for field "UserGlobalPlanSubscription.plan_category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ApplicableGroupMode(); ok {
		if err := userglobalplansubscription.ApplicableGroupModeValidator(v); err != nil {
			return &ValidationError{Name: "applicable_group_mode", err: fmt.Errorf(`ent: validator failed for field "UserGlobalPlanSubscription.applicable_group_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := userglobalplansubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserGlobalPlanSubscription.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaPeriod(); ok {
		if err := userglobalplansubscription.QuotaPeriodValidator(v); err != nil {
			return &ValidationError{Name: "quota_period", err: fmt.Errorf(`ent: validator failed for field "UserGlobalPlanSubscription.quota_period": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlanNameSnapshot(); ok {
		if err := userglobalplansubscription.PlanNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "plan_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "UserGlobalPlanSubscription.plan_name_snapshot": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserGlobalPlanSubscription.user"`)
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserGlobalPlanSubscription.plan"`)
	}
	return nil
}

func (_u *UserGlobalPlanSubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userglobalplansubscription.Table, userglobalplansubscription.Columns, sqlgraph.NewFieldSpec(userglobalplansubscription.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(userglobalplansubscription.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(userglobalplansubscription.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PlanCategory(); ok {
		_spec.SetField(userglobalplansubscription.FieldPlanCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApplicableGroupMode(); ok {
		_spec.SetField(userglobalplansubscription.FieldApplicableGroupMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApplicableGroupIds(); ok {
		_spec.SetField(userglobalplansubscription.FieldApplicableGroupIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedApplicableGroupIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, userglobalplansubscription.FieldApplicableGroupIds, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(userglobalplansubscription.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(userglobalplansubscription.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(userglobalplansubscription.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(userglobalplansubscription.FieldCurrentPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(userglobalplansubscription.FieldCurrentPeriodEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.QuotaPeriod(); ok {
		_spec.SetField(userglobalplansubscription.FieldQuotaPeriod, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaLimitUsd(); ok {
		_spec.SetField(userglobalplansubscription.FieldQuotaLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaLimitUsd(); ok {
		_spec.AddField(userglobalplansubscription.FieldQuotaLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaUsedUsd(); ok {
		_spec.SetField(userglobalplansubscription.FieldQuotaUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsedUsd(); ok {
		_spec.AddField(userglobalplansubscription.FieldQuotaUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TierRank(); ok {
		_spec.SetField(userglobalplansubscription.FieldTierRank, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTierRank(); ok {
		_spec.AddField(userglobalplansubscription.FieldTierRank, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PlanNameSnapshot(); ok {
		_spec.SetField(userglobalplansubscription.FieldPlanNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(userglobalplansubscription.FieldAssignedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(userglobalplansubscription.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(userglobalplansubscription.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.LastResetAt(); ok {
		_spec.SetField(userglobalplansubscription.FieldLastResetAt, field.TypeTime, value)
	}
	if _u.mutation.LastResetAtCleared() {
		_spec.ClearField(userglobalplansubscription.FieldLastResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(userglobalplansubscription.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(userglobalplansubscription.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userglobalplansubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.UserTable,
			Columns: []string{userglobalplansubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.UserTable,
			Columns: []string{userglobalplansubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.PlanTable,
			Columns: []string{userglobalplansubscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.PlanTable,
			Columns: []string{userglobalplansubscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.SourceOrderTable,
			Columns: []string{userglobalplansubscription.SourceOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.SourceOrderTable,
			Columns: []string{userglobalplansubscription.SourceOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.AssignedByUserTable,
			Columns: []string{userglobalplansubscription.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.AssignedByUserTable,
			Columns: []string{userglobalplansubscription.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userglobalplansubscription.UsageLogsTable,
			Columns: []string{userglobalplansubscription.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userglobalplansubscription.UsageLogsTable,
			Columns: []string{userglobalplansubscription.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userglobalplansubscription.UsageLogsTable,
			Columns: []string{userglobalplansubscription.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userglobalplansubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserGlobalPlanSubscriptionUpdateOne is the builder for updating a single UserGlobalPlanSubscription entity.
type UserGlobalPlanSubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserGlobalPlanSubscriptionMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetDeletedAt(v time.Time) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableDeletedAt(v *time.Time) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) ClearDeletedAt() *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetUserID(v int64) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableUserID(v *int64) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetPlanID(v int64) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillablePlanID(v *int64) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetPlanCategory sets the "plan_category" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetPlanCategory(v string) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetPlanCategory(v)
	return _u
}

// SetNillablePlanCategory sets the "plan_category" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillablePlanCategory(v *string) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetPlanCategory(*v)
	}
	return _u
}

// SetApplicableGroupMode sets the "applicable_group_mode" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetApplicableGroupMode(v string) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetApplicableGroupMode(v)
	return _u
}

// SetNillableApplicableGroupMode sets the "applicable_group_mode" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableApplicableGroupMode(v *string) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetApplicableGroupMode(*v)
	}
	return _u
}

// SetApplicableGroupIds sets the "applicable_group_ids" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetApplicableGroupIds(v []int64) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetApplicableGroupIds(v)
	return _u
}

// AppendApplicableGroupIds appends value to the "applicable_group_ids" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) AppendApplicableGroupIds(v []int64) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.AppendApplicableGroupIds(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetStatus(v string) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableStatus(v *string) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetStartsAt(v time.Time) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableStartsAt(v *time.Time) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetExpiresAt(v time.Time) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableExpiresAt(v *time.Time) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetCurrentPeriodStart(v time.Time) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetCurrentPeriodStart(v)
	return _u
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableCurrentPeriodStart(v *time.Time) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetCurrentPeriodStart(*v)
	}
	return _u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetCurrentPeriodEnd(v time.Time) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetCurrentPeriodEnd(v)
	return _u
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableCurrentPeriodEnd(v *time.Time) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetCurrentPeriodEnd(*v)
	}
	return _u
}

// SetQuotaPeriod sets the "quota_period" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetQuotaPeriod(v string) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetQuotaPeriod(v)
	return _u
}

// SetNillableQuotaPeriod sets the "quota_period" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableQuotaPeriod(v *string) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetQuotaPeriod(*v)
	}
	return _u
}

// SetQuotaLimitUsd sets the "quota_limit_usd" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetQuotaLimitUsd(v float64) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.ResetQuotaLimitUsd()
	_u.mutation.SetQuotaLimitUsd(v)
	return _u
}

// SetNillableQuotaLimitUsd sets the "quota_limit_usd" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableQuotaLimitUsd(v *float64) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetQuotaLimitUsd(*v)
	}
	return _u
}

// AddQuotaLimitUsd adds value to the "quota_limit_usd" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) AddQuotaLimitUsd(v float64) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.AddQuotaLimitUsd(v)
	return _u
}

// SetQuotaUsedUsd sets the "quota_used_usd" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetQuotaUsedUsd(v float64) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.ResetQuotaUsedUsd()
	_u.mutation.SetQuotaUsedUsd(v)
	return _u
}

// SetNillableQuotaUsedUsd sets the "quota_used_usd" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableQuotaUsedUsd(v *float64) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetQuotaUsedUsd(*v)
	}
	return _u
}

// AddQuotaUsedUsd adds value to the "quota_used_usd" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) AddQuotaUsedUsd(v float64) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.AddQuotaUsedUsd(v)
	return _u
}

// SetTierRank sets the "tier_rank" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetTierRank(v int) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.ResetTierRank()
	_u.mutation.SetTierRank(v)
	return _u
}

// SetNillableTierRank sets the "tier_rank" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableTierRank(v *int) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetTierRank(*v)
	}
	return _u
}

// AddTierRank adds value to the "tier_rank" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) AddTierRank(v int) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.AddTierRank(v)
	return _u
}

// SetPlanNameSnapshot sets the "plan_name_snapshot" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetPlanNameSnapshot(v string) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetPlanNameSnapshot(v)
	return _u
}

// SetNillablePlanNameSnapshot sets the "plan_name_snapshot" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillablePlanNameSnapshot(v *string) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetPlanNameSnapshot(*v)
	}
	return _u
}

// SetSourceOrderID sets the "source_order_id" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetSourceOrderID(v int64) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetSourceOrderID(v)
	return _u
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableSourceOrderID(v *int64) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetSourceOrderID(*v)
	}
	return _u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) ClearSourceOrderID() *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.ClearSourceOrderID()
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetAssignedBy(v int64) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableAssignedBy(v *int64) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) ClearAssignedBy() *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.ClearAssignedBy()
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetAssignedAt(v time.Time) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableAssignedAt(v *time.Time) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNotes(v string) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableNotes(v *string) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) ClearNotes() *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetLastResetAt sets the "last_reset_at" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetLastResetAt(v time.Time) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetLastResetAt(v)
	return _u
}

// SetNillableLastResetAt sets the "last_reset_at" field if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableLastResetAt(v *time.Time) *UserGlobalPlanSubscriptionUpdateOne {
	if v != nil {
		_u.SetLastResetAt(*v)
	}
	return _u
}

// ClearLastResetAt clears the value of the "last_reset_at" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) ClearLastResetAt() *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.ClearLastResetAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetMetadata(v map[string]interface{}) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) ClearMetadata() *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetUpdatedAt(v time.Time) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetUser(v *User) *UserGlobalPlanSubscriptionUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetPlan(v *SubscriptionPlan) *UserGlobalPlanSubscriptionUpdateOne {
	return _u.SetPlanID(v.ID)
}

// SetSourceOrder sets the "source_order" edge to the PaymentOrder entity.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetSourceOrder(v *PaymentOrder) *UserGlobalPlanSubscriptionUpdateOne {
	return _u.SetSourceOrderID(v.ID)
}

// SetAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetAssignedByUserID(id int64) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.SetAssignedByUserID(id)
	return _u
}

// SetNillableAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetNillableAssignedByUserID(id *int64) *UserGlobalPlanSubscriptionUpdateOne {
	if id != nil {
		_u = _u.SetAssignedByUserID(*id)
	}
	return _u
}

// SetAssignedByUser sets the "assigned_by_user" edge to the User entity.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SetAssignedByUser(v *User) *UserGlobalPlanSubscriptionUpdateOne {
	return _u.SetAssignedByUserID(v.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *UserGlobalPlanSubscriptionUpdateOne) AddUsageLogIDs(ids ...int64) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *UserGlobalPlanSubscriptionUpdateOne) AddUsageLogs(v ...*UsageLog) *UserGlobalPlanSubscriptionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the UserGlobalPlanSubscriptionMutation object of the builder.
func (_u *UserGlobalPlanSubscriptionUpdateOne) Mutation() *UserGlobalPlanSubscriptionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserGlobalPlanSubscriptionUpdateOne) ClearUser() *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearPlan clears the "plan" edge to the SubscriptionPlan entity.
func (_u *UserGlobalPlanSubscriptionUpdateOne) ClearPlan() *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// ClearSourceOrder clears the "source_order" edge to the PaymentOrder entity.
func (_u *UserGlobalPlanSubscriptionUpdateOne) ClearSourceOrder() *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.ClearSourceOrder()
	return _u
}

// ClearAssignedByUser clears the "assigned_by_user" edge to the User entity.
func (_u *UserGlobalPlanSubscriptionUpdateOne) ClearAssignedByUser() *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.ClearAssignedByUser()
	return _u
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *UserGlobalPlanSubscriptionUpdateOne) ClearUsageLogs() *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *UserGlobalPlanSubscriptionUpdateOne) RemoveUsageLogIDs(ids ...int64) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *UserGlobalPlanSubscriptionUpdateOne) RemoveUsageLogs(v ...*UsageLog) *UserGlobalPlanSubscriptionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Where appends a list predicates to the UserGlobalPlanSubscriptionUpdate builder.
func (_u *UserGlobalPlanSubscriptionUpdateOne) Where(ps ...predicate.UserGlobalPlanSubscription) *UserGlobalPlanSubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserGlobalPlanSubscriptionUpdateOne) Select(field string, fields ...string) *UserGlobalPlanSubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserGlobalPlanSubscription entity.
func (_u *UserGlobalPlanSubscriptionUpdateOne) Save(ctx context.Context) (*UserGlobalPlanSubscription, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserGlobalPlanSubscriptionUpdateOne) SaveX(ctx context.Context) *UserGlobalPlanSubscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserGlobalPlanSubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserGlobalPlanSubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserGlobalPlanSubscriptionUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if userglobalplansubscription.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized userglobalplansubscription.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := userglobalplansubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserGlobalPlanSubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.PlanCategory(); ok {
		if err := userglobalplansubscription.PlanCategoryValidator(v); err != nil {
			return &ValidationError{Name: "plan_category", err: fmt.Errorf(`ent: validator failed for field "UserGlobalPlanSubscription.plan_category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ApplicableGroupMode(); ok {
		if err := userglobalplansubscription.ApplicableGroupModeValidator(v); err != nil {
			return &ValidationError{Name: "applicable_group_mode", err: fmt.Errorf(`ent: validator failed for field "UserGlobalPlanSubscription.applicable_group_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := userglobalplansubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserGlobalPlanSubscription.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaPeriod(); ok {
		if err := userglobalplansubscription.QuotaPeriodValidator(v); err != nil {
			return &ValidationError{Name: "quota_period", err: fmt.Errorf(`ent: validator failed for field "UserGlobalPlanSubscription.quota_period": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlanNameSnapshot(); ok {
		if err := userglobalplansubscription.PlanNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "plan_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "UserGlobalPlanSubscription.plan_name_snapshot": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserGlobalPlanSubscription.user"`)
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserGlobalPlanSubscription.plan"`)
	}
	return nil
}

func (_u *UserGlobalPlanSubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *UserGlobalPlanSubscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userglobalplansubscription.Table, userglobalplansubscription.Columns, sqlgraph.NewFieldSpec(userglobalplansubscription.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserGlobalPlanSubscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userglobalplansubscription.FieldID)
		for _, f := range fields {
			if !userglobalplansubscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userglobalplansubscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(userglobalplansubscription.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(userglobalplansubscription.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PlanCategory(); ok {
		_spec.SetField(userglobalplansubscription.FieldPlanCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApplicableGroupMode(); ok {
		_spec.SetField(userglobalplansubscription.FieldApplicableGroupMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApplicableGroupIds(); ok {
		_spec.SetField(userglobalplansubscription.FieldApplicableGroupIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedApplicableGroupIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, userglobalplansubscription.FieldApplicableGroupIds, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(userglobalplansubscription.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(userglobalplansubscription.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(userglobalplansubscription.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(userglobalplansubscription.FieldCurrentPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(userglobalplansubscription.FieldCurrentPeriodEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.QuotaPeriod(); ok {
		_spec.SetField(userglobalplansubscription.FieldQuotaPeriod, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaLimitUsd(); ok {
		_spec.SetField(userglobalplansubscription.FieldQuotaLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaLimitUsd(); ok {
		_spec.AddField(userglobalplansubscription.FieldQuotaLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaUsedUsd(); ok {
		_spec.SetField(userglobalplansubscription.FieldQuotaUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsedUsd(); ok {
		_spec.AddField(userglobalplansubscription.FieldQuotaUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TierRank(); ok {
		_spec.SetField(userglobalplansubscription.FieldTierRank, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTierRank(); ok {
		_spec.AddField(userglobalplansubscription.FieldTierRank, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PlanNameSnapshot(); ok {
		_spec.SetField(userglobalplansubscription.FieldPlanNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(userglobalplansubscription.FieldAssignedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(userglobalplansubscription.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(userglobalplansubscription.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.LastResetAt(); ok {
		_spec.SetField(userglobalplansubscription.FieldLastResetAt, field.TypeTime, value)
	}
	if _u.mutation.LastResetAtCleared() {
		_spec.ClearField(userglobalplansubscription.FieldLastResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(userglobalplansubscription.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(userglobalplansubscription.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userglobalplansubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.UserTable,
			Columns: []string{userglobalplansubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.UserTable,
			Columns: []string{userglobalplansubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.PlanTable,
			Columns: []string{userglobalplansubscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.PlanTable,
			Columns: []string{userglobalplansubscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.SourceOrderTable,
			Columns: []string{userglobalplansubscription.SourceOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.SourceOrderTable,
			Columns: []string{userglobalplansubscription.SourceOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.AssignedByUserTable,
			Columns: []string{userglobalplansubscription.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userglobalplansubscription.AssignedByUserTable,
			Columns: []string{userglobalplansubscription.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userglobalplansubscription.UsageLogsTable,
			Columns: []string{userglobalplansubscription.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userglobalplansubscription.UsageLogsTable,
			Columns: []string{userglobalplansubscription.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userglobalplansubscription.UsageLogsTable,
			Columns: []string{userglobalplansubscription.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserGlobalPlanSubscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userglobalplansubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
