// Code generated by ent, DO NOT EDIT.

package creemproductbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldID, id))
}

// ProviderInstanceID applies equality check predicate on the "provider_instance_id" field. It's identical to ProviderInstanceIDEQ.
func ProviderInstanceID(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldProviderInstanceID, v))
}

// ExternalProductID applies equality check predicate on the "external_product_id" field. It's identical to ExternalProductIDEQ.
func ExternalProductID(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldExternalProductID, v))
}

// TargetType applies equality check predicate on the "target_type" field. It's identical to TargetTypeEQ.
func TargetType(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldTargetType, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldPlanID, v))
}

// CreditedBalance applies equality check predicate on the "credited_balance" field. It's identical to CreditedBalanceEQ.
func CreditedBalance(v float64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldCreditedBalance, v))
}

// ProductName applies equality check predicate on the "product_name" field. It's identical to ProductNameEQ.
func ProductName(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldProductName, v))
}

// PriceMinor applies equality check predicate on the "price_minor" field. It's identical to PriceMinorEQ.
func PriceMinor(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldPriceMinor, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldCurrency, v))
}

// BillingType applies equality check predicate on the "billing_type" field. It's identical to BillingTypeEQ.
func BillingType(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldBillingType, v))
}

// ProductStatus applies equality check predicate on the "product_status" field. It's identical to ProductStatusEQ.
func ProductStatus(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldProductStatus, v))
}

// TaxMode applies equality check predicate on the "tax_mode" field. It's identical to TaxModeEQ.
func TaxMode(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldTaxMode, v))
}

// Environment applies equality check predicate on the "environment" field. It's identical to EnvironmentEQ.
func Environment(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldEnvironment, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldEnabled, v))
}

// HealthStatus applies equality check predicate on the "health_status" field. It's identical to HealthStatusEQ.
func HealthStatus(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldHealthStatus, v))
}

// HealthReason applies equality check predicate on the "health_reason" field. It's identical to HealthReasonEQ.
func HealthReason(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldHealthReason, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldSortOrder, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldLastSyncedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderInstanceIDEQ applies the EQ predicate on the "provider_instance_id" field.
func ProviderInstanceIDEQ(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldProviderInstanceID, v))
}

// ProviderInstanceIDNEQ applies the NEQ predicate on the "provider_instance_id" field.
func ProviderInstanceIDNEQ(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldProviderInstanceID, v))
}

// ProviderInstanceIDIn applies the In predicate on the "provider_instance_id" field.
func ProviderInstanceIDIn(vs ...int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldProviderInstanceID, vs...))
}

// ProviderInstanceIDNotIn applies the NotIn predicate on the "provider_instance_id" field.
func ProviderInstanceIDNotIn(vs ...int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldProviderInstanceID, vs...))
}

// ProviderInstanceIDGT applies the GT predicate on the "provider_instance_id" field.
func ProviderInstanceIDGT(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldProviderInstanceID, v))
}

// ProviderInstanceIDGTE applies the GTE predicate on the "provider_instance_id" field.
func ProviderInstanceIDGTE(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldProviderInstanceID, v))
}

// ProviderInstanceIDLT applies the LT predicate on the "provider_instance_id" field.
func ProviderInstanceIDLT(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldProviderInstanceID, v))
}

// ProviderInstanceIDLTE applies the LTE predicate on the "provider_instance_id" field.
func ProviderInstanceIDLTE(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldProviderInstanceID, v))
}

// ExternalProductIDEQ applies the EQ predicate on the "external_product_id" field.
func ExternalProductIDEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldExternalProductID, v))
}

// ExternalProductIDNEQ applies the NEQ predicate on the "external_product_id" field.
func ExternalProductIDNEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldExternalProductID, v))
}

// ExternalProductIDIn applies the In predicate on the "external_product_id" field.
func ExternalProductIDIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldExternalProductID, vs...))
}

// ExternalProductIDNotIn applies the NotIn predicate on the "external_product_id" field.
func ExternalProductIDNotIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldExternalProductID, vs...))
}

// ExternalProductIDGT applies the GT predicate on the "external_product_id" field.
func ExternalProductIDGT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldExternalProductID, v))
}

// ExternalProductIDGTE applies the GTE predicate on the "external_product_id" field.
func ExternalProductIDGTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldExternalProductID, v))
}

// ExternalProductIDLT applies the LT predicate on the "external_product_id" field.
func ExternalProductIDLT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldExternalProductID, v))
}

// ExternalProductIDLTE applies the LTE predicate on the "external_product_id" field.
func ExternalProductIDLTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldExternalProductID, v))
}

// ExternalProductIDContains applies the Contains predicate on the "external_product_id" field.
func ExternalProductIDContains(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContains(FieldExternalProductID, v))
}

// ExternalProductIDHasPrefix applies the HasPrefix predicate on the "external_product_id" field.
func ExternalProductIDHasPrefix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasPrefix(FieldExternalProductID, v))
}

// ExternalProductIDHasSuffix applies the HasSuffix predicate on the "external_product_id" field.
func ExternalProductIDHasSuffix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasSuffix(FieldExternalProductID, v))
}

// ExternalProductIDEqualFold applies the EqualFold predicate on the "external_product_id" field.
func ExternalProductIDEqualFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEqualFold(FieldExternalProductID, v))
}

// ExternalProductIDContainsFold applies the ContainsFold predicate on the "external_product_id" field.
func ExternalProductIDContainsFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContainsFold(FieldExternalProductID, v))
}

// TargetTypeEQ applies the EQ predicate on the "target_type" field.
func TargetTypeEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldTargetType, v))
}

// TargetTypeNEQ applies the NEQ predicate on the "target_type" field.
func TargetTypeNEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldTargetType, v))
}

// TargetTypeIn applies the In predicate on the "target_type" field.
func TargetTypeIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldTargetType, vs...))
}

// TargetTypeNotIn applies the NotIn predicate on the "target_type" field.
func TargetTypeNotIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldTargetType, vs...))
}

// TargetTypeGT applies the GT predicate on the "target_type" field.
func TargetTypeGT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldTargetType, v))
}

// TargetTypeGTE applies the GTE predicate on the "target_type" field.
func TargetTypeGTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldTargetType, v))
}

// TargetTypeLT applies the LT predicate on the "target_type" field.
func TargetTypeLT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldTargetType, v))
}

// TargetTypeLTE applies the LTE predicate on the "target_type" field.
func TargetTypeLTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldTargetType, v))
}

// TargetTypeContains applies the Contains predicate on the "target_type" field.
func TargetTypeContains(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContains(FieldTargetType, v))
}

// TargetTypeHasPrefix applies the HasPrefix predicate on the "target_type" field.
func TargetTypeHasPrefix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasPrefix(FieldTargetType, v))
}

// TargetTypeHasSuffix applies the HasSuffix predicate on the "target_type" field.
func TargetTypeHasSuffix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasSuffix(FieldTargetType, v))
}

// TargetTypeEqualFold applies the EqualFold predicate on the "target_type" field.
func TargetTypeEqualFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEqualFold(FieldTargetType, v))
}

// TargetTypeContainsFold applies the ContainsFold predicate on the "target_type" field.
func TargetTypeContainsFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContainsFold(FieldTargetType, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldPlanID, vs...))
}

// PlanIDGT applies the GT predicate on the "plan_id" field.
func PlanIDGT(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldPlanID, v))
}

// PlanIDGTE applies the GTE predicate on the "plan_id" field.
func PlanIDGTE(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldPlanID, v))
}

// PlanIDLT applies the LT predicate on the "plan_id" field.
func PlanIDLT(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldPlanID, v))
}

// PlanIDLTE applies the LTE predicate on the "plan_id" field.
func PlanIDLTE(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldPlanID, v))
}

// PlanIDIsNil applies the IsNil predicate on the "plan_id" field.
func PlanIDIsNil() predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIsNull(FieldPlanID))
}

// PlanIDNotNil applies the NotNil predicate on the "plan_id" field.
func PlanIDNotNil() predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotNull(FieldPlanID))
}

// CreditedBalanceEQ applies the EQ predicate on the "credited_balance" field.
func CreditedBalanceEQ(v float64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldCreditedBalance, v))
}

// CreditedBalanceNEQ applies the NEQ predicate on the "credited_balance" field.
func CreditedBalanceNEQ(v float64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldCreditedBalance, v))
}

// CreditedBalanceIn applies the In predicate on the "credited_balance" field.
func CreditedBalanceIn(vs ...float64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldCreditedBalance, vs...))
}

// CreditedBalanceNotIn applies the NotIn predicate on the "credited_balance" field.
func CreditedBalanceNotIn(vs ...float64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldCreditedBalance, vs...))
}

// CreditedBalanceGT applies the GT predicate on the "credited_balance" field.
func CreditedBalanceGT(v float64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldCreditedBalance, v))
}

// CreditedBalanceGTE applies the GTE predicate on the "credited_balance" field.
func CreditedBalanceGTE(v float64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldCreditedBalance, v))
}

// CreditedBalanceLT applies the LT predicate on the "credited_balance" field.
func CreditedBalanceLT(v float64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldCreditedBalance, v))
}

// CreditedBalanceLTE applies the LTE predicate on the "credited_balance" field.
func CreditedBalanceLTE(v float64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldCreditedBalance, v))
}

// CreditedBalanceIsNil applies the IsNil predicate on the "credited_balance" field.
func CreditedBalanceIsNil() predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIsNull(FieldCreditedBalance))
}

// CreditedBalanceNotNil applies the NotNil predicate on the "credited_balance" field.
func CreditedBalanceNotNil() predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotNull(FieldCreditedBalance))
}

// ProductNameEQ applies the EQ predicate on the "product_name" field.
func ProductNameEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldProductName, v))
}

// ProductNameNEQ applies the NEQ predicate on the "product_name" field.
func ProductNameNEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldProductName, v))
}

// ProductNameIn applies the In predicate on the "product_name" field.
func ProductNameIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldProductName, vs...))
}

// ProductNameNotIn applies the NotIn predicate on the "product_name" field.
func ProductNameNotIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldProductName, vs...))
}

// ProductNameGT applies the GT predicate on the "product_name" field.
func ProductNameGT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldProductName, v))
}

// ProductNameGTE applies the GTE predicate on the "product_name" field.
func ProductNameGTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldProductName, v))
}

// ProductNameLT applies the LT predicate on the "product_name" field.
func ProductNameLT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldProductName, v))
}

// ProductNameLTE applies the LTE predicate on the "product_name" field.
func ProductNameLTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldProductName, v))
}

// ProductNameContains applies the Contains predicate on the "product_name" field.
func ProductNameContains(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContains(FieldProductName, v))
}

// ProductNameHasPrefix applies the HasPrefix predicate on the "product_name" field.
func ProductNameHasPrefix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasPrefix(FieldProductName, v))
}

// ProductNameHasSuffix applies the HasSuffix predicate on the "product_name" field.
func ProductNameHasSuffix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasSuffix(FieldProductName, v))
}

// ProductNameEqualFold applies the EqualFold predicate on the "product_name" field.
func ProductNameEqualFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEqualFold(FieldProductName, v))
}

// ProductNameContainsFold applies the ContainsFold predicate on the "product_name" field.
func ProductNameContainsFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContainsFold(FieldProductName, v))
}

// PriceMinorEQ applies the EQ predicate on the "price_minor" field.
func PriceMinorEQ(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldPriceMinor, v))
}

// PriceMinorNEQ applies the NEQ predicate on the "price_minor" field.
func PriceMinorNEQ(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldPriceMinor, v))
}

// PriceMinorIn applies the In predicate on the "price_minor" field.
func PriceMinorIn(vs ...int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldPriceMinor, vs...))
}

// PriceMinorNotIn applies the NotIn predicate on the "price_minor" field.
func PriceMinorNotIn(vs ...int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldPriceMinor, vs...))
}

// PriceMinorGT applies the GT predicate on the "price_minor" field.
func PriceMinorGT(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldPriceMinor, v))
}

// PriceMinorGTE applies the GTE predicate on the "price_minor" field.
func PriceMinorGTE(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldPriceMinor, v))
}

// PriceMinorLT applies the LT predicate on the "price_minor" field.
func PriceMinorLT(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldPriceMinor, v))
}

// PriceMinorLTE applies the LTE predicate on the "price_minor" field.
func PriceMinorLTE(v int64) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldPriceMinor, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContainsFold(FieldCurrency, v))
}

// BillingTypeEQ applies the EQ predicate on the "billing_type" field.
func BillingTypeEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldBillingType, v))
}

// BillingTypeNEQ applies the NEQ predicate on the "billing_type" field.
func BillingTypeNEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldBillingType, v))
}

// BillingTypeIn applies the In predicate on the "billing_type" field.
func BillingTypeIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldBillingType, vs...))
}

// BillingTypeNotIn applies the NotIn predicate on the "billing_type" field.
func BillingTypeNotIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldBillingType, vs...))
}

// BillingTypeGT applies the GT predicate on the "billing_type" field.
func BillingTypeGT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldBillingType, v))
}

// BillingTypeGTE applies the GTE predicate on the "billing_type" field.
func BillingTypeGTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldBillingType, v))
}

// BillingTypeLT applies the LT predicate on the "billing_type" field.
func BillingTypeLT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldBillingType, v))
}

// BillingTypeLTE applies the LTE predicate on the "billing_type" field.
func BillingTypeLTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldBillingType, v))
}

// BillingTypeContains applies the Contains predicate on the "billing_type" field.
func BillingTypeContains(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContains(FieldBillingType, v))
}

// BillingTypeHasPrefix applies the HasPrefix predicate on the "billing_type" field.
func BillingTypeHasPrefix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasPrefix(FieldBillingType, v))
}

// BillingTypeHasSuffix applies the HasSuffix predicate on the "billing_type" field.
func BillingTypeHasSuffix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasSuffix(FieldBillingType, v))
}

// BillingTypeEqualFold applies the EqualFold predicate on the "billing_type" field.
func BillingTypeEqualFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEqualFold(FieldBillingType, v))
}

// BillingTypeContainsFold applies the ContainsFold predicate on the "billing_type" field.
func BillingTypeContainsFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContainsFold(FieldBillingType, v))
}

// ProductStatusEQ applies the EQ predicate on the "product_status" field.
func ProductStatusEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldProductStatus, v))
}

// ProductStatusNEQ applies the NEQ predicate on the "product_status" field.
func ProductStatusNEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldProductStatus, v))
}

// ProductStatusIn applies the In predicate on the "product_status" field.
func ProductStatusIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldProductStatus, vs...))
}

// ProductStatusNotIn applies the NotIn predicate on the "product_status" field.
func ProductStatusNotIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldProductStatus, vs...))
}

// ProductStatusGT applies the GT predicate on the "product_status" field.
func ProductStatusGT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldProductStatus, v))
}

// ProductStatusGTE applies the GTE predicate on the "product_status" field.
func ProductStatusGTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldProductStatus, v))
}

// ProductStatusLT applies the LT predicate on the "product_status" field.
func ProductStatusLT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldProductStatus, v))
}

// ProductStatusLTE applies the LTE predicate on the "product_status" field.
func ProductStatusLTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldProductStatus, v))
}

// ProductStatusContains applies the Contains predicate on the "product_status" field.
func ProductStatusContains(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContains(FieldProductStatus, v))
}

// ProductStatusHasPrefix applies the HasPrefix predicate on the "product_status" field.
func ProductStatusHasPrefix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasPrefix(FieldProductStatus, v))
}

// ProductStatusHasSuffix applies the HasSuffix predicate on the "product_status" field.
func ProductStatusHasSuffix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasSuffix(FieldProductStatus, v))
}

// ProductStatusEqualFold applies the EqualFold predicate on the "product_status" field.
func ProductStatusEqualFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEqualFold(FieldProductStatus, v))
}

// ProductStatusContainsFold applies the ContainsFold predicate on the "product_status" field.
func ProductStatusContainsFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContainsFold(FieldProductStatus, v))
}

// TaxModeEQ applies the EQ predicate on the "tax_mode" field.
func TaxModeEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldTaxMode, v))
}

// TaxModeNEQ applies the NEQ predicate on the "tax_mode" field.
func TaxModeNEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldTaxMode, v))
}

// TaxModeIn applies the In predicate on the "tax_mode" field.
func TaxModeIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldTaxMode, vs...))
}

// TaxModeNotIn applies the NotIn predicate on the "tax_mode" field.
func TaxModeNotIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldTaxMode, vs...))
}

// TaxModeGT applies the GT predicate on the "tax_mode" field.
func TaxModeGT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldTaxMode, v))
}

// TaxModeGTE applies the GTE predicate on the "tax_mode" field.
func TaxModeGTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldTaxMode, v))
}

// TaxModeLT applies the LT predicate on the "tax_mode" field.
func TaxModeLT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldTaxMode, v))
}

// TaxModeLTE applies the LTE predicate on the "tax_mode" field.
func TaxModeLTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldTaxMode, v))
}

// TaxModeContains applies the Contains predicate on the "tax_mode" field.
func TaxModeContains(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContains(FieldTaxMode, v))
}

// TaxModeHasPrefix applies the HasPrefix predicate on the "tax_mode" field.
func TaxModeHasPrefix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasPrefix(FieldTaxMode, v))
}

// TaxModeHasSuffix applies the HasSuffix predicate on the "tax_mode" field.
func TaxModeHasSuffix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasSuffix(FieldTaxMode, v))
}

// TaxModeEqualFold applies the EqualFold predicate on the "tax_mode" field.
func TaxModeEqualFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEqualFold(FieldTaxMode, v))
}

// TaxModeContainsFold applies the ContainsFold predicate on the "tax_mode" field.
func TaxModeContainsFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContainsFold(FieldTaxMode, v))
}

// EnvironmentEQ applies the EQ predicate on the "environment" field.
func EnvironmentEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldEnvironment, v))
}

// EnvironmentNEQ applies the NEQ predicate on the "environment" field.
func EnvironmentNEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldEnvironment, v))
}

// EnvironmentIn applies the In predicate on the "environment" field.
func EnvironmentIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldEnvironment, vs...))
}

// EnvironmentNotIn applies the NotIn predicate on the "environment" field.
func EnvironmentNotIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldEnvironment, vs...))
}

// EnvironmentGT applies the GT predicate on the "environment" field.
func EnvironmentGT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldEnvironment, v))
}

// EnvironmentGTE applies the GTE predicate on the "environment" field.
func EnvironmentGTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldEnvironment, v))
}

// EnvironmentLT applies the LT predicate on the "environment" field.
func EnvironmentLT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldEnvironment, v))
}

// EnvironmentLTE applies the LTE predicate on the "environment" field.
func EnvironmentLTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldEnvironment, v))
}

// EnvironmentContains applies the Contains predicate on the "environment" field.
func EnvironmentContains(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContains(FieldEnvironment, v))
}

// EnvironmentHasPrefix applies the HasPrefix predicate on the "environment" field.
func EnvironmentHasPrefix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasPrefix(FieldEnvironment, v))
}

// EnvironmentHasSuffix applies the HasSuffix predicate on the "environment" field.
func EnvironmentHasSuffix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasSuffix(FieldEnvironment, v))
}

// EnvironmentEqualFold applies the EqualFold predicate on the "environment" field.
func EnvironmentEqualFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEqualFold(FieldEnvironment, v))
}

// EnvironmentContainsFold applies the ContainsFold predicate on the "environment" field.
func EnvironmentContainsFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContainsFold(FieldEnvironment, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldEnabled, v))
}

// HealthStatusEQ applies the EQ predicate on the "health_status" field.
func HealthStatusEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldHealthStatus, v))
}

// HealthStatusNEQ applies the NEQ predicate on the "health_status" field.
func HealthStatusNEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldHealthStatus, v))
}

// HealthStatusIn applies the In predicate on the "health_status" field.
func HealthStatusIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldHealthStatus, vs...))
}

// HealthStatusNotIn applies the NotIn predicate on the "health_status" field.
func HealthStatusNotIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldHealthStatus, vs...))
}

// HealthStatusGT applies the GT predicate on the "health_status" field.
func HealthStatusGT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldHealthStatus, v))
}

// HealthStatusGTE applies the GTE predicate on the "health_status" field.
func HealthStatusGTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldHealthStatus, v))
}

// HealthStatusLT applies the LT predicate on the "health_status" field.
func HealthStatusLT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldHealthStatus, v))
}

// HealthStatusLTE applies the LTE predicate on the "health_status" field.
func HealthStatusLTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldHealthStatus, v))
}

// HealthStatusContains applies the Contains predicate on the "health_status" field.
func HealthStatusContains(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContains(FieldHealthStatus, v))
}

// HealthStatusHasPrefix applies the HasPrefix predicate on the "health_status" field.
func HealthStatusHasPrefix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasPrefix(FieldHealthStatus, v))
}

// HealthStatusHasSuffix applies the HasSuffix predicate on the "health_status" field.
func HealthStatusHasSuffix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasSuffix(FieldHealthStatus, v))
}

// HealthStatusEqualFold applies the EqualFold predicate on the "health_status" field.
func HealthStatusEqualFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEqualFold(FieldHealthStatus, v))
}

// HealthStatusContainsFold applies the ContainsFold predicate on the "health_status" field.
func HealthStatusContainsFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContainsFold(FieldHealthStatus, v))
}

// HealthReasonEQ applies the EQ predicate on the "health_reason" field.
func HealthReasonEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldHealthReason, v))
}

// HealthReasonNEQ applies the NEQ predicate on the "health_reason" field.
func HealthReasonNEQ(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldHealthReason, v))
}

// HealthReasonIn applies the In predicate on the "health_reason" field.
func HealthReasonIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldHealthReason, vs...))
}

// HealthReasonNotIn applies the NotIn predicate on the "health_reason" field.
func HealthReasonNotIn(vs ...string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldHealthReason, vs...))
}

// HealthReasonGT applies the GT predicate on the "health_reason" field.
func HealthReasonGT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldHealthReason, v))
}

// HealthReasonGTE applies the GTE predicate on the "health_reason" field.
func HealthReasonGTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldHealthReason, v))
}

// HealthReasonLT applies the LT predicate on the "health_reason" field.
func HealthReasonLT(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldHealthReason, v))
}

// HealthReasonLTE applies the LTE predicate on the "health_reason" field.
func HealthReasonLTE(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldHealthReason, v))
}

// HealthReasonContains applies the Contains predicate on the "health_reason" field.
func HealthReasonContains(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContains(FieldHealthReason, v))
}

// HealthReasonHasPrefix applies the HasPrefix predicate on the "health_reason" field.
func HealthReasonHasPrefix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasPrefix(FieldHealthReason, v))
}

// HealthReasonHasSuffix applies the HasSuffix predicate on the "health_reason" field.
func HealthReasonHasSuffix(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldHasSuffix(FieldHealthReason, v))
}

// HealthReasonEqualFold applies the EqualFold predicate on the "health_reason" field.
func HealthReasonEqualFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEqualFold(FieldHealthReason, v))
}

// HealthReasonContainsFold applies the ContainsFold predicate on the "health_reason" field.
func HealthReasonContainsFold(v string) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldContainsFold(FieldHealthReason, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldSortOrder, v))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastSyncedAtIsNil applies the IsNil predicate on the "last_synced_at" field.
func LastSyncedAtIsNil() predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIsNull(FieldLastSyncedAt))
}

// LastSyncedAtNotNil applies the NotNil predicate on the "last_synced_at" field.
func LastSyncedAtNotNil() predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotNull(FieldLastSyncedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CreemProductBinding) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CreemProductBinding) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CreemProductBinding) predicate.CreemProductBinding {
	return predicate.CreemProductBinding(sql.NotPredicates(p))
}
