// Code generated by ent, DO NOT EDIT.

package userglobalplansubscription

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the userglobalplansubscription type in the database.
	Label = "user_global_plan_subscription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPlanID holds the string denoting the plan_id field in the database.
	FieldPlanID = "plan_id"
	// FieldPlanCategory holds the string denoting the plan_category field in the database.
	FieldPlanCategory = "plan_category"
	// FieldApplicableGroupMode holds the string denoting the applicable_group_mode field in the database.
	FieldApplicableGroupMode = "applicable_group_mode"
	// FieldApplicableGroupIds holds the string denoting the applicable_group_ids field in the database.
	FieldApplicableGroupIds = "applicable_group_ids"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStartsAt holds the string denoting the starts_at field in the database.
	FieldStartsAt = "starts_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCurrentPeriodStart holds the string denoting the current_period_start field in the database.
	FieldCurrentPeriodStart = "current_period_start"
	// FieldCurrentPeriodEnd holds the string denoting the current_period_end field in the database.
	FieldCurrentPeriodEnd = "current_period_end"
	// FieldQuotaPeriod holds the string denoting the quota_period field in the database.
	FieldQuotaPeriod = "quota_period"
	// FieldQuotaLimitUsd holds the string denoting the quota_limit_usd field in the database.
	FieldQuotaLimitUsd = "quota_limit_usd"
	// FieldQuotaUsedUsd holds the string denoting the quota_used_usd field in the database.
	FieldQuotaUsedUsd = "quota_used_usd"
	// FieldTierRank holds the string denoting the tier_rank field in the database.
	FieldTierRank = "tier_rank"
	// FieldPlanNameSnapshot holds the string denoting the plan_name_snapshot field in the database.
	FieldPlanNameSnapshot = "plan_name_snapshot"
	// FieldSourceOrderID holds the string denoting the source_order_id field in the database.
	FieldSourceOrderID = "source_order_id"
	// FieldAssignedBy holds the string denoting the assigned_by field in the database.
	FieldAssignedBy = "assigned_by"
	// FieldAssignedAt holds the string denoting the assigned_at field in the database.
	FieldAssignedAt = "assigned_at"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldLastResetAt holds the string denoting the last_reset_at field in the database.
	FieldLastResetAt = "last_reset_at"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgePlan holds the string denoting the plan edge name in mutations.
	EdgePlan = "plan"
	// EdgeSourceOrder holds the string denoting the source_order edge name in mutations.
	EdgeSourceOrder = "source_order"
	// EdgeAssignedByUser holds the string denoting the assigned_by_user edge name in mutations.
	EdgeAssignedByUser = "assigned_by_user"
	// EdgeUsageLogs holds the string denoting the usage_logs edge name in mutations.
	EdgeUsageLogs = "usage_logs"
	// Table holds the table name of the userglobalplansubscription in the database.
	Table = "user_global_plan_subscriptions"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_global_plan_subscriptions"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// PlanTable is the table that holds the plan relation/edge.
	PlanTable = "user_global_plan_subscriptions"
	// PlanInverseTable is the table name for the SubscriptionPlan entity.
	// It exists in this package in order to avoid circular dependency with the "subscriptionplan" package.
	PlanInverseTable = "subscription_plans"
	// PlanColumn is the table column denoting the plan relation/edge.
	PlanColumn = "plan_id"
	// SourceOrderTable is the table that holds the source_order relation/edge.
	SourceOrderTable = "user_global_plan_subscriptions"
	// SourceOrderInverseTable is the table name for the PaymentOrder entity.
	// It exists in this package in order to avoid circular dependency with the "paymentorder" package.
	SourceOrderInverseTable = "payment_orders"
	// SourceOrderColumn is the table column denoting the source_order relation/edge.
	SourceOrderColumn = "source_order_id"
	// AssignedByUserTable is the table that holds the assigned_by_user relation/edge.
	AssignedByUserTable = "user_global_plan_subscriptions"
	// AssignedByUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AssignedByUserInverseTable = "users"
	// AssignedByUserColumn is the table column denoting the assigned_by_user relation/edge.
	AssignedByUserColumn = "assigned_by"
	// UsageLogsTable is the table that holds the usage_logs relation/edge.
	UsageLogsTable = "usage_logs"
	// UsageLogsInverseTable is the table name for the UsageLog entity.
	// It exists in this package in order to avoid circular dependency with the "usagelog" package.
	UsageLogsInverseTable = "usage_logs"
	// UsageLogsColumn is the table column denoting the usage_logs relation/edge.
	UsageLogsColumn = "global_plan_subscription_id"
)

// Columns holds all SQL columns for userglobalplansubscription fields.
var Columns = []string{
	FieldID,
	FieldDeletedAt,
	FieldUserID,
	FieldPlanID,
	FieldPlanCategory,
	FieldApplicableGroupMode,
	FieldApplicableGroupIds,
	FieldStatus,
	FieldStartsAt,
	FieldExpiresAt,
	FieldCurrentPeriodStart,
	FieldCurrentPeriodEnd,
	FieldQuotaPeriod,
	FieldQuotaLimitUsd,
	FieldQuotaUsedUsd,
	FieldTierRank,
	FieldPlanNameSnapshot,
	FieldSourceOrderID,
	FieldAssignedBy,
	FieldAssignedAt,
	FieldNotes,
	FieldLastResetAt,
	FieldMetadata,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultPlanCategory holds the default value on creation for the "plan_category" field.
	DefaultPlanCategory string
	// PlanCategoryValidator is a validator for the "plan_category" field. It is called by the builders before save.
	PlanCategoryValidator func(string) error
	// DefaultApplicableGroupMode holds the default value on creation for the "applicable_group_mode" field.
	DefaultApplicableGroupMode string
	// ApplicableGroupModeValidator is a validator for the "applicable_group_mode" field. It is called by the builders before save.
	ApplicableGroupModeValidator func(string) error
	// DefaultApplicableGroupIds holds the default value on creation for the "applicable_group_ids" field.
	DefaultApplicableGroupIds []int64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultQuotaPeriod holds the default value on creation for the "quota_period" field.
	DefaultQuotaPeriod string
	// QuotaPeriodValidator is a validator for the "quota_period" field. It is called by the builders before save.
	QuotaPeriodValidator func(string) error
	// DefaultQuotaLimitUsd holds the default value on creation for the "quota_limit_usd" field.
	DefaultQuotaLimitUsd float64
	// DefaultQuotaUsedUsd holds the default value on creation for the "quota_used_usd" field.
	DefaultQuotaUsedUsd float64
	// DefaultTierRank holds the default value on creation for the "tier_rank" field.
	DefaultTierRank int
	// DefaultPlanNameSnapshot holds the default value on creation for the "plan_name_snapshot" field.
	DefaultPlanNameSnapshot string
	// PlanNameSnapshotValidator is a validator for the "plan_name_snapshot" field. It is called by the builders before save.
	PlanNameSnapshotValidator func(string) error
	// DefaultAssignedAt holds the default value on creation for the "assigned_at" field.
	DefaultAssignedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserGlobalPlanSubscription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPlanID orders the results by the plan_id field.
func ByPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanID, opts...).ToFunc()
}

// ByPlanCategory orders the results by the plan_category field.
func ByPlanCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanCategory, opts...).ToFunc()
}

// ByApplicableGroupMode orders the results by the applicable_group_mode field.
func ByApplicableGroupMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApplicableGroupMode, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStartsAt orders the results by the starts_at field.
func ByStartsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartsAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCurrentPeriodStart orders the results by the current_period_start field.
func ByCurrentPeriodStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentPeriodStart, opts...).ToFunc()
}

// ByCurrentPeriodEnd orders the results by the current_period_end field.
func ByCurrentPeriodEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentPeriodEnd, opts...).ToFunc()
}

// ByQuotaPeriod orders the results by the quota_period field.
func ByQuotaPeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaPeriod, opts...).ToFunc()
}

// ByQuotaLimitUsd orders the results by the quota_limit_usd field.
func ByQuotaLimitUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaLimitUsd, opts...).ToFunc()
}

// ByQuotaUsedUsd orders the results by the quota_used_usd field.
func ByQuotaUsedUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaUsedUsd, opts...).ToFunc()
}

// ByTierRank orders the results by the tier_rank field.
func ByTierRank(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTierRank, opts...).ToFunc()
}

// ByPlanNameSnapshot orders the results by the plan_name_snapshot field.
func ByPlanNameSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanNameSnapshot, opts...).ToFunc()
}

// BySourceOrderID orders the results by the source_order_id field.
func BySourceOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceOrderID, opts...).ToFunc()
}

// ByAssignedBy orders the results by the assigned_by field.
func ByAssignedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedBy, opts...).ToFunc()
}

// ByAssignedAt orders the results by the assigned_at field.
func ByAssignedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedAt, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByLastResetAt orders the results by the last_reset_at field.
func ByLastResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastResetAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByPlanField orders the results by plan field.
func ByPlanField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlanStep(), sql.OrderByField(field, opts...))
	}
}

// BySourceOrderField orders the results by source_order field.
func BySourceOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceOrderStep(), sql.OrderByField(field, opts...))
	}
}

// ByAssignedByUserField orders the results by assigned_by_user field.
func ByAssignedByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssignedByUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByUsageLogsCount orders the results by usage_logs count.
func ByUsageLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsageLogsStep(), opts...)
	}
}

// ByUsageLogs orders the results by usage_logs terms.
func ByUsageLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsageLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newPlanStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlanInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
	)
}
func newSourceOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceOrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SourceOrderTable, SourceOrderColumn),
	)
}
func newAssignedByUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssignedByUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AssignedByUserTable, AssignedByUserColumn),
	)
}
func newUsageLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsageLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
	)
}
